import { GroceryItem } from './types';

/**
 * Format grocery list for export (text format)
 */
export function formatGroceryListForExport(
  groceryList: GroceryItem[],
  weekDate?: string,
): string {
  const date = weekDate || new Date().toLocaleDateString('en-SG', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const lines: string[] = [];

  lines.push('🛒 MakanPlan Grocery List');
  lines.push(`📅 Week of ${date}`);
  lines.push('');

  // Group by category
  const categories: Record<string, GroceryItem[]> = {
    Protein: [],
    Veg: [],
    Pantry: [],
    Other: [],
  };

  groceryList.forEach((item) => {
    const category = item.category || 'Other';
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(item);
  });

  // Format each category
  Object.entries(categories).forEach(([category, items]) => {
    if (items.length > 0) {
      lines.push(`${getCategoryEmoji(category)} ${category.toUpperCase()}`);
      items.forEach((item) => {
        const checkbox = item.isChecked ? '☑️' : '☐';
        lines.push(`  ${checkbox} ${item.name}`);
      });
      lines.push('');
    }
  });

  lines.push('---');
  lines.push('Generated by MakanPlan');
  lines.push('https://makanplan.app');

  return lines.join('\n');
}

/**
 * Get emoji for category
 */
function getCategoryEmoji(category: string): string {
  const emojis: Record<string, string> = {
    Protein: '🍗',
    Veg: '🥬',
    Pantry: '🏪',
    Other: '📦',
  };
  return emojis[category] || '📦';
}

/**
 * Format grocery list as CSV (for spreadsheet import)
 */
export function formatGroceryListAsCSV(groceryList: GroceryItem[]): string {
  const lines: string[] = [];

  // Header
  lines.push('Category,Item,Checked');

  // Data rows
  groceryList.forEach((item) => {
    const category = item.category || 'Other';
    const checked = item.isChecked ? 'Yes' : 'No';
    // Escape quotes in item names
    const itemName = `"${item.name.replace(/"/g, '""')}"`;
    lines.push(`${category},${itemName},${checked}`);
  });

  return lines.join('\n');
}

/**
 * Generate email body for grocery list
 */
export function generateEmailBody(
  groceryList: GroceryItem[],
  weekDate?: string,
): string {
  return formatGroceryListForExport(groceryList, weekDate);
}

/**
 * Generate subject line for email
 */
export function generateEmailSubject(weekDate?: string): string {
  const date = weekDate || new Date().toLocaleDateString('en-SG', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  return `MakanPlan Grocery List - Week of ${date}`;
}
