import { Recipe } from './types';

export const FAMILY_RECIPES: Recipe[] = [
  {
    id: 'chicken_broccoli_family',
    name: 'Chicken with Broccoli',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: [
      '600g chicken breast or thighs',
      '1 head broccoli',
      '3 cloves garlic, chopped',
      '2 slices ginger',
      '3 tbsp soy sauce',
      '1 tbsp oyster sauce',
      '½ tsp salt',
      '1 tsp sugar',
      '2 tsp cooking wine',
      '⅓ tsp white pepper',
      '1 tbsp cornstarch',
      '2 tbsp water',
      '1 tsp sesame oil',
      '2 carrots, sliced',
      '2 green onions',
    ],
    instructions: `Marinate chicken with cornstarch, water, salt, and white pepper. Blanch broccoli in boiling water with oil and salt for 3 mins until almost cooked. Heat wok with oil on medium heat, shallow fry chicken until 80% done (about 2 mins), then set aside. Add aromatics (garlic, ginger, green onion whites) until fragrant. Add broccoli and carrots, stir-fry on high heat for 1-2 mins. Splash cooking wine on wok sides. Add back chicken and stir quickly. Pour in mixed sauce (soy sauce, oyster sauce, salt, sugar, cooking wine, white pepper) while stirring. Taste test. Add cornstarch slurry gradually to achieve desired sauce thickness. Finish with sesame oil for shine before serving.`,
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'three_cup_chicken_family',
    name: 'Three-Cup Chicken Claypot',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: [
      '2 lbs chicken (thighs, breast with skin, or wings)',
      '7 slices ginger',
      '2 dried red chillies',
      '3 green onion stalks (stems and leaves separated)',
      '12 garlic cloves, sliced',
      '4 shallots',
      '1 basil stalk',
      '6 tbsp rice wine',
      '3 tbsp dark soy sauce',
      '3 tbsp light soy sauce',
      '2 tbsp sesame oil',
      '1 tbsp Huatiao wine',
      '1 tbsp sugar',
      '1 tbsp Shaoxing wine',
      'Salt and pepper for marinade',
      '1 tbsp cornflour for marinade',
      '1 tbsp water for marinade',
    ],
    instructions: `Marinate chicken pieces with salt, pepper, cornflour, and water. Heat wok with oil and fry ginger, shallots, and sliced garlic until fragrant. Add dried red chillies and green onion stems. Add chicken and fry until golden brown on both sides, keeping aromatics on top. Make a hole in the middle and add sugar to caramelize. Add half the gravy mixture (rice wine, dark soy, light soy, sesame oil) and stir until caramelized. Transfer all ingredients to a heated claypot. Add basil and remaining gravy. Cover and stew for 3-4 minutes on low heat, stirring once. Drizzle Shaoxing wine over top. Serve with green onion leaves on top.`,
    servings: 4,
    cuisineType: 'Western',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'salmon_rice_onepot_family',
    name: 'Garlic Soy Salmon and Cabbage One-Pot Rice',
    type: 'rice_noodle_one_pot',
    protein: 'fish',
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: [
      '3-4 cloves garlic, chopped',
      '400g salmon, cut into slices',
      '¼ cabbage, sliced into triangles',
      '2 cups rice',
      '2-3 mushrooms, sliced',
      '5 tsp soy sauce',
      '1 tbsp sake',
      '2-3 tsp sugar',
      'Salt to taste',
      '1 tbsp oil',
    ],
    instructions: `Cook rice in rice cooker with sake. Chop garlic and set aside 1 clove for vegetables. Slice cabbage and mushrooms into bite-sized pieces. Slice salmon into bite-sized pieces. Make sauce by combining 3 cloves chopped garlic, 2 tsp sugar, and 5 tsp soy sauce. In a pan, add oil and 1 clove garlic, heat until fragrant. Add mushrooms and cabbage with a dash of salt and water. Cook until done and set aside. In the same pan, add salmon skin-side down (no oil needed). When half cooked, add sauce and cook until done. Place vegetables and salmon on top of rice and serve hot.`,
    servings: 3,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'salmon_foil_family',
    name: 'Salmon in Aluminium Foil',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: [
      '2 salmon fillets (240g)',
      'Salt and black pepper to taste',
      '½ onion',
      '5cm carrot',
      '50g shimeji mushrooms',
      '2 shiitake mushrooms',
      '2 green onion strands',
      '1½ tbsp unsalted butter',
      '1 tbsp sake',
      '2 tbsp soy sauce or ponzu',
    ],
    instructions: `Preheat oven to 400°F (200°C). Prepare foil packets by placing salmon fillets on center of foil. Season with salt and pepper. Slice onion, carrot, and mushrooms. Arrange vegetables around salmon. Top each fillet with butter and sake. Drizzle with soy sauce or ponzu. Fold foil to create sealed packets. Bake for 12-15 minutes until salmon is cooked through. Carefully open foil (watch for steam) and serve hot with green onions on top.`,
    servings: 2,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
];
