import { Recipe } from './types';

export const SEED_RECIPES: Recipe[] = [
  // Protein mains - Chicken
  {
    id: 'chicken_teriyaki',
    name: 'Chicken Teriyaki',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['chicken breast', 'soy sauce', 'mirin', 'sake', 'garlic', 'ginger'],
    instructions: 'Pan-fry chicken, coat with teriyaki glaze. Serve with rice.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'thai_chicken_basil',
    name: 'Thai Chicken with Holy Basil',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ['chicken', 'holy basil', 'garlic', 'chilli', 'fish sauce', 'lime'],
    instructions: 'Stir-fry chicken with garlic, chilli, and basil. Finish with lime.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'cantonese_chicken_soy',
    name: 'Cantonese Soy Chicken',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['chicken thighs', 'soy sauce', 'star anise', 'ginger', 'scallions'],
    instructions: 'Braise chicken in soy sauce with aromatics until tender.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'vietnamese_chicken_lemongrass',
    name: 'Vietnamese Lemongrass Chicken',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['chicken', 'lemongrass', 'garlic', 'fish sauce', 'lime', 'chilli'],
    instructions: 'Marinate and grill chicken with lemongrass. Serve with lime.',
    servings: 4,
    cuisineType: 'Vietnamese',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },

  // Protein mains - Fish
  {
    id: 'fish_miso_butter',
    name: 'Miso Butter Fish',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['white fish fillet', 'miso', 'butter', 'sake', 'scallions'],
    instructions: 'Pan-sear fish, top with miso butter. Bake until cooked through.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'thai_fish_curry',
    name: 'Thai Green Fish Curry',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['fish fillet', 'green curry paste', 'coconut milk', 'Thai basil', 'bamboo shoots'],
    instructions: 'Simmer fish in green curry with coconut milk and vegetables.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'cantonese_steamed_fish',
    name: 'Steamed Fish with Ginger & Scallions',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['whole fish', 'ginger', 'scallions', 'soy sauce', 'oil'],
    instructions: 'Steam fish with ginger and scallions. Drizzle with hot oil and soy sauce.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Protein mains - Seafood
  {
    id: 'seafood_tofu_claypot',
    name: 'Seafood Tofu Clay Pot',
    type: 'rice_noodle_one_pot',
    protein: 'seafood',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['shrimp', 'scallops', 'tofu', 'napa cabbage', 'mushrooms', 'soy sauce'],
    instructions: 'Cook seafood and tofu in clay pot with napa cabbage and broth.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'thai_shrimp_paste',
    name: 'Thai Shrimp Paste Stir-Fry',
    type: 'protein_main',
    protein: 'seafood',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['shrimp', 'shrimp paste', 'garlic', 'chilli', 'long beans', 'lime'],
    instructions: 'Stir-fry shrimp with shrimp paste, garlic, and long beans.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },

  // Protein mains - Tofu
  {
    id: 'tofu_mapo',
    name: 'Mapo Tofu',
    type: 'protein_main',
    protein: 'tofu',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['silken tofu', 'fermented bean paste', 'garlic', 'ginger', 'Sichuan pepper', 'scallions'],
    instructions: 'Simmer tofu in spicy bean paste sauce. Serve with rice.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'medium',
    createdAt: Date.now(),
  },
  {
    id: 'tofu_agedashi',
    name: 'Agedashi Tofu',
    type: 'protein_main',
    protein: 'tofu',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ['firm tofu', 'potato starch', 'dashi', 'soy sauce', 'mirin', 'scallions'],
    instructions: 'Deep-fry tofu cubes, serve in hot dashi broth.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Rice/Noodle one-pots
  {
    id: 'chicken_rice_claypot',
    name: 'Chicken Rice Clay Pot',
    type: 'rice_noodle_one_pot',
    protein: 'chicken',
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ['chicken', 'rice', 'soy sauce', 'mushrooms', 'peas', 'scallions'],
    instructions: 'Cook rice with chicken and vegetables in clay pot.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'pad_thai',
    name: 'Pad Thai',
    type: 'rice_noodle_one_pot',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['rice noodles', 'shrimp', 'chicken', 'bean sprouts', 'peanuts', 'lime', 'fish sauce'],
    instructions: 'Stir-fry noodles with protein and vegetables. Serve with lime and peanuts.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'chicken_noodle_soup',
    name: 'Chicken Noodle Soup',
    type: 'rice_noodle_one_pot',
    protein: 'chicken',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['chicken', 'egg noodles', 'bok choy', 'mushrooms', 'ginger', 'scallions'],
    instructions: 'Simmer chicken in broth with noodles and vegetables.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Veg sides
  {
    id: 'broccoli_garlic',
    name: 'Garlic Broccoli',
    type: 'veg_side',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['broccoli', 'garlic', 'oil', 'soy sauce'],
    instructions: 'Stir-fry broccoli with garlic until tender-crisp.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'mixed_veg_stir_fry',
    name: 'Mixed Vegetable Stir-Fry',
    type: 'veg_side',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['carrots', 'bell peppers', 'snap peas', 'mushrooms', 'garlic', 'oil'],
    instructions: 'Stir-fry mixed vegetables with garlic until tender-crisp.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'cabbage_stir_fry',
    name: 'Stir-Fried Cabbage',
    type: 'veg_side',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['cabbage', 'garlic', 'oil', 'soy sauce'],
    instructions: 'Stir-fry cabbage with garlic until wilted.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'kangkong_garlic',
    name: 'Kangkong with Garlic',
    type: 'veg_side',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['kangkong', 'garlic', 'oil', 'soy sauce'],
    instructions: 'Stir-fry kangkong with garlic until tender.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'bok_choy_oyster',
    name: 'Bok Choy with Oyster Sauce',
    type: 'veg_side',
    protein: 'mixed',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['bok choy', 'garlic', 'oyster sauce', 'oil'],
    instructions: 'Stir-fry bok choy with garlic and oyster sauce.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
];
