import { Recipe } from './types';

export const SEED_RECIPES: Recipe[] = [
  // Protein mains - Chicken
  {
    id: 'chicken_teriyaki',
    name: 'Chicken Teriyaki',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['600g chicken breast', '3 tbsp soy sauce', '2 tbsp mirin', '1 tbsp sake', '3 cloves garlic', '1 tbsp ginger'],
    instructions: 'Pan-fry chicken, coat with teriyaki glaze. Serve with rice.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'thai_chicken_basil',
    name: 'Thai Chicken with Holy Basil',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ['600g chicken', '1 cup holy basil', '4 cloves garlic', '2 red chillies', '2 tbsp fish sauce', '2 limes'],
    instructions: 'Stir-fry chicken with garlic, chilli, and basil. Finish with lime.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'cantonese_chicken_soy',
    name: 'Cantonese Soy Chicken',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['800g chicken thighs', '4 tbsp soy sauce', '2 star anise', '3 slices ginger', '3 scallions'],
    instructions: 'Braise chicken in soy sauce with aromatics until tender.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'vietnamese_chicken_lemongrass',
    name: 'Vietnamese Lemongrass Chicken',
    type: 'protein_main',
    protein: 'chicken',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['600g chicken', '3 lemongrass stalks', '4 cloves garlic', '3 tbsp fish sauce', '2 limes', '2 red chillies'],
    instructions: 'Marinate and grill chicken with lemongrass. Serve with lime.',
    servings: 4,
    cuisineType: 'Vietnamese',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },

  // Protein mains - Fish
  {
    id: 'fish_miso_butter',
    name: 'Miso Butter Fish',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['600g white fish fillet', '3 tbsp miso', '2 tbsp butter', '1 tbsp sake', '2 scallions'],
    instructions: 'Pan-fry fish, top with miso butter sauce. Serve with rice.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'fish_thai_curry',
    name: 'Thai Red Curry Fish',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['600g fish fillet', '3 tbsp red curry paste', '1 can coconut milk', '1 bell pepper', '1 cup basil', '2 tbsp fish sauce'],
    instructions: 'Simmer fish in red curry and coconut milk with vegetables.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'fish_steamed_soy',
    name: 'Steamed Fish with Soy',
    type: 'protein_main',
    protein: 'fish',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['600g whole fish or fillet', '4 tbsp soy sauce', '2 tbsp sesame oil', '4 slices ginger', '3 scallions'],
    instructions: 'Steam fish with ginger and scallions. Drizzle with soy and sesame oil.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Protein mains - Beef
  {
    id: 'beef_stir_fry',
    name: 'Beef Stir-Fry with Peppers',
    type: 'protein_main',
    protein: 'beef',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['500g beef sirloin', '2 bell peppers', '1 onion', '4 cloves garlic', '3 tbsp soy sauce', '2 tbsp oyster sauce'],
    instructions: 'Stir-fry beef with peppers and onions until cooked through.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'beef_rendang',
    name: 'Beef Rendang',
    type: 'protein_main',
    protein: 'beef',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['600g beef', '1 can coconut milk', '4 tbsp rendang paste', '3 lemongrass stalks', '4 lime leaves', '2 tbsp tamarind'],
    instructions: 'Simmer beef in rendang paste and coconut milk until tender.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },

  // Protein mains - Seafood
  {
    id: 'shrimp_garlic',
    name: 'Garlic Butter Shrimp',
    type: 'protein_main',
    protein: 'seafood',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['600g large shrimp', '6 cloves garlic', '4 tbsp butter', '2 tbsp white wine', '2 tbsp parsley'],
    instructions: 'Sauté shrimp in garlic butter until pink. Finish with white wine.',
    servings: 4,
    cuisineType: 'Western',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'squid_chilli',
    name: 'Chilli Squid',
    type: 'protein_main',
    protein: 'seafood',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['600g squid', '4 red chillies', '4 cloves garlic', '3 tbsp soy sauce', '2 tbsp fish sauce', '1 lime'],
    instructions: 'Stir-fry squid with chilli and garlic. Finish with lime juice.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'clams_white_wine',
    name: 'Clams in White Wine',
    type: 'protein_main',
    protein: 'seafood',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['800g clams', '1 cup white wine', '4 cloves garlic', '2 tbsp butter', '2 tbsp parsley'],
    instructions: 'Steam clams in white wine with garlic and butter.',
    servings: 4,
    cuisineType: 'Western',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Protein mains - Tofu
  {
    id: 'tofu_mapo',
    name: 'Mapo Tofu',
    type: 'protein_main',
    protein: 'tofu',
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['500g silken tofu', '3 tbsp doubanjiang', '4 cloves garlic', '2 tbsp chilli oil', '2 tbsp Sichuan peppercorn'],
    instructions: 'Simmer tofu in spicy doubanjiang sauce with aromatics.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'tofu_agedashi',
    name: 'Agedashi Tofu',
    type: 'protein_main',
    protein: 'tofu',
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['500g firm tofu', '4 tbsp potato starch', '3 tbsp soy sauce', '2 tbsp dashi', '2 tbsp mirin', '2 scallions'],
    instructions: 'Deep-fry tofu until golden. Serve in dashi-based sauce.',
    servings: 4,
    cuisineType: 'Japanese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Rice/Noodle one-pots
  {
    id: 'chicken_rice_claypot',
    name: 'Chicken Rice Claypot',
    type: 'rice_noodle_one_pot',
    protein: 'chicken',
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ['2 cups rice', '400g chicken', '3 mushrooms', '2 scallions', '3 tbsp soy sauce', '1 tbsp sesame oil'],
    instructions: 'Cook rice with chicken and mushrooms in claypot. Drizzle with soy and sesame oil.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'pad_thai',
    name: 'Pad Thai',
    type: 'rice_noodle_one_pot',
    protein: 'seafood',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['300g rice noodles', '200g shrimp', '100g chicken', '1 cup bean sprouts', '3 tbsp peanuts', '2 limes', '3 tbsp fish sauce'],
    instructions: 'Stir-fry noodles with protein and vegetables. Serve with lime and peanuts.',
    servings: 4,
    cuisineType: 'Thai',
    spiceLevel: 'light-medium',
    createdAt: Date.now(),
  },
  {
    id: 'chicken_noodle_soup',
    name: 'Chicken Noodle Soup',
    type: 'rice_noodle_one_pot',
    protein: 'chicken',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['400g chicken', '200g egg noodles', '200g bok choy', '150g mushrooms', '2 slices ginger', '3 scallions'],
    instructions: 'Simmer chicken in broth with noodles and vegetables.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },

  // Veg sides
  {
    id: 'broccoli_garlic',
    name: 'Garlic Broccoli',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['500g broccoli', '4 cloves garlic', '2 tbsp oil', '2 tbsp soy sauce'],
    instructions: 'Stir-fry broccoli with garlic until tender-crisp.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'mixed_veg_stir_fry',
    name: 'Mixed Vegetable Stir-Fry',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['200g carrots', '200g bell peppers', '150g snap peas', '150g mushrooms', '3 cloves garlic', '2 tbsp oil'],
    instructions: 'Stir-fry mixed vegetables with garlic until tender-crisp.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'cabbage_stir_fry',
    name: 'Stir-Fried Cabbage',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['500g cabbage', '4 cloves garlic', '2 tbsp oil', '2 tbsp soy sauce'],
    instructions: 'Stir-fry cabbage with garlic until wilted.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'kangkong_garlic',
    name: 'Kangkong with Garlic',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ['500g kangkong', '4 cloves garlic', '2 tbsp oil', '2 tbsp soy sauce'],
    instructions: 'Stir-fry kangkong with garlic until tender.',
    servings: 4,
    cuisineType: 'Mixed',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'bok_choy_oyster',
    name: 'Bok Choy with Oyster Sauce',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ['600g bok choy', '3 cloves garlic', '3 tbsp oyster sauce', '2 tbsp oil'],
    instructions: 'Stir-fry bok choy with garlic and oyster sauce.',
    servings: 4,
    cuisineType: 'Cantonese',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'asparagus_garlic',
    name: 'Garlic Asparagus',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['500g asparagus', '4 cloves garlic', '2 tbsp oil', '1 tbsp soy sauce'],
    instructions: 'Stir-fry asparagus with garlic until tender.',
    servings: 4,
    cuisineType: 'Western',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
  {
    id: 'spinach_garlic',
    name: 'Garlic Spinach',
    type: 'veg_side',
    protein: 'tofu',
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ['400g spinach', '4 cloves garlic', '2 tbsp oil', '1 tbsp soy sauce'],
    instructions: 'Quickly stir-fry spinach with garlic until wilted.',
    servings: 4,
    cuisineType: 'Western',
    spiceLevel: 'light',
    createdAt: Date.now(),
  },
];
