import { Recipe } from './types';

/**
 * User's curated 44 recipes (exported from MakanPlan)
 * This is the source of truth for the app's recipe library
 */
export const USER_RECIPES: Recipe[] = [
  {
    id: 'chicken_broccoli_family',
    name: 'Chicken with Broccoli',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["600g chicken breast or thighs", "1 head broccoli", "3 cloves garlic, chopped", "2 slices ginger", "3 tbsp soy sauce", "1 tbsp oyster sauce", "\u00bd tsp salt", "1 tsp sugar", "2 tsp cooking wine", "\u2153 tsp white pepper", "1 tbsp cornstarch", "2 tbsp water", "1 tsp sesame oil", "2 carrots, sliced", "2 green onions"],
    instructions: 'Marinate chicken with cornstarch, water, salt, and white pepper. Blanch broccoli in boiling water with oil and salt for 3 mins until almost cooked. Heat wok with oil on medium heat, shallow fry chicken until 80% done (about 2 mins), then set aside. Add aromatics (garlic, ginger, green onion whites) until fragrant. Add broccoli and carrots, stir-fry on high heat for 1-2 mins. Splash cooking wine on wok sides. Add back chicken and stir quickly. Pour in mixed sauce (soy sauce, oyster sauce, salt, sugar, cooking wine, white pepper) while stirring. Taste test. Add cornstarch slurry gradually to achieve desired sauce thickness. Finish with sesame oil for shine before serving.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'three_cup_chicken_family',
    name: 'Three-Cup Chicken Claypot',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["2 lbs chicken (thighs, breast with skin, or wings)", "7 slices ginger", "2 dried red chillies", "3 green onion stalks (stems and leaves separated)", "12 garlic cloves, sliced", "4 shallots", "1 basil stalk", "6 tbsp rice wine", "3 tbsp dark soy sauce", "3 tbsp light soy sauce", "2 tbsp sesame oil", "1 tbsp Huatiao wine", "1 tbsp sugar", "1 tbsp Shaoxing wine", "Salt and pepper for marinade", "1 tbsp cornflour for marinade", "1 tbsp water for marinade"],
    instructions: 'Marinate chicken pieces with salt, pepper, cornflour, and water. Heat wok with oil and fry ginger, shallots, and sliced garlic until fragrant. Add dried red chillies and green onion stems. Add chicken and fry until golden brown on both sides, keeping aromatics on top. Make a hole in the middle and add sugar to caramelize. Add half the gravy mixture (rice wine, dark soy, light soy, sesame oil) and stir until caramelized. Transfer all ingredients to a heated claypot. Add basil and remaining gravy. Cover and stew for 3-4 minutes on low heat, stirring once. Drizzle Shaoxing wine over top. Serve with green onion leaves on top.',
    servings: 4,
    cuisineType: 'Taiwanese' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'salmon_rice_onepot_family',
    name: 'Garlic Soy Salmon and Cabbage One-Pot Rice',
    type: 'rice_noodle_one_pot' as const,
    protein: 'fish' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ["3-4 cloves garlic, chopped", "400g salmon, cut into slices", "\u00bc cabbage, sliced into triangles", "2 cups rice", "2-3 mushrooms, sliced", "5 tsp soy sauce", "1 tbsp sake", "2-3 tsp sugar", "Salt to taste", "1 tbsp oil"],
    instructions: 'Cook rice in rice cooker with sake. Chop garlic and set aside 1 clove for vegetables. Slice cabbage and mushrooms into bite-sized pieces. Slice salmon into bite-sized pieces. Make sauce by combining 3 cloves chopped garlic, 2 tsp sugar, and 5 tsp soy sauce. In a pan, add oil and 1 clove garlic, heat until fragrant. Add mushrooms and cabbage with a dash of salt and water. Cook until done and set aside. In the same pan, add salmon skin-side down (no oil needed). When half cooked, add sauce and cook until done. Place vegetables and salmon on top of rice and serve hot.',
    servings: 3,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'salmon_foil_family',
    name: 'Salmon in Aluminium Foil',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["2 salmon fillets (240g)", "Salt and black pepper to taste", "\u00bd onion", "5cm carrot", "50g shimeji mushrooms", "2 shiitake mushrooms", "2 green onion strands", "1\u00bd tbsp unsalted butter", "1 tbsp sake", "2 tbsp soy sauce or ponzu"],
    instructions: 'Preheat oven to 400°F (200°C). Prepare foil packets by placing salmon fillets on center of foil. Season with salt and pepper. Slice onion, carrot, and mushrooms. Arrange vegetables around salmon. Top each fillet with butter and sake. Drizzle with soy sauce or ponzu. Fold foil to create sealed packets. Bake for 12-15 minutes until salmon is cooked through. Carefully open foil (watch for steam) and serve hot with green onions on top.',
    servings: 2,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'thai_chicken_basil',
    name: 'Thai Chicken with Holy Basil',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["600g chicken", "1 cup holy basil", "4 cloves garlic", "2 red chillies", "2 tbsp fish sauce", "2 limes"],
    instructions: 'Stir-fry chicken with garlic, chilli, and basil. Finish with lime.',
    servings: 4,
    cuisineType: 'Thai' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'vietnamese_chicken_lemongrass',
    name: 'Vietnamese Lemongrass Chicken',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["600g chicken", "3 lemongrass stalks", "4 cloves garlic", "3 tbsp fish sauce", "2 limes", "2 red chillies"],
    instructions: 'Marinate and grill chicken with lemongrass. Serve with lime.',
    servings: 4,
    cuisineType: 'Vietnamese' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'fish_miso_butter',
    name: 'Miso Butter Fish',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["600g white fish fillet", "3 tbsp miso", "2 tbsp butter", "1 tbsp sake", "2 scallions"],
    instructions: 'Pan-fry fish, top with miso butter sauce. Serve with rice.',
    servings: 4,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'beef_stir_fry',
    name: 'Beef Stir-Fry with Peppers',
    type: 'protein_main' as const,
    protein: 'beef' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["500g beef sirloin", "2 bell peppers", "1 onion", "4 cloves garlic", "3 tbsp soy sauce", "2 tbsp oyster sauce"],
    instructions: 'Stir-fry beef with peppers and onions until cooked through.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'tofu_mapo',
    name: 'Mapo Tofu',
    type: 'protein_main' as const,
    protein: 'tofu' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["500g silken tofu", "3 tbsp doubanjiang", "4 cloves garlic", "2 tbsp chilli oil", "2 tbsp Sichuan peppercorn"],
    instructions: 'Simmer tofu in spicy doubanjiang sauce with aromatics.',
    servings: 4,
    cuisineType: 'Mixed' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'tofu_agedashi',
    name: 'Agedashi Tofu',
    type: 'protein_main' as const,
    protein: 'tofu' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["500g firm tofu", "4 tbsp potato starch", "3 tbsp soy sauce", "2 tbsp dashi", "2 tbsp mirin", "2 scallions"],
    instructions: 'Deep-fry tofu until golden. Serve in dashi-based sauce.',
    servings: 4,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'chicken_rice_claypot',
    name: 'Chicken Rice Claypot',
    type: 'rice_noodle_one_pot' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["2 cups rice", "400g chicken", "3 mushrooms", "2 scallions", "3 tbsp soy sauce", "1 tbsp sesame oil"],
    instructions: 'Cook rice with chicken and mushrooms in claypot. Drizzle with soy and sesame oil.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'pad_thai',
    name: 'Pad Thai',
    type: 'rice_noodle_one_pot' as const,
    protein: 'seafood' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["300g rice noodles", "200g shrimp", "100g chicken", "1 cup bean sprouts", "3 tbsp peanuts", "2 limes", "3 tbsp fish sauce"],
    instructions: 'Stir-fry noodles with protein and vegetables. Serve with lime and peanuts.',
    servings: 4,
    cuisineType: 'Thai' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'chicken_noodle_soup',
    name: 'Chicken Noodle Soup',
    type: 'rice_noodle_one_pot' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["400g chicken", "200g egg noodles", "200g bok choy", "150g mushrooms", "2 slices ginger", "3 scallions"],
    instructions: 'Simmer chicken in broth with noodles and vegetables.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'mixed_veg_stir_fry',
    name: 'Mixed Vegetable Stir-Fry',
    type: 'veg_side' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["200g carrots", "200g bell peppers", "150g snap peas", "150g mushrooms", "3 cloves garlic", "2 tbsp oil"],
    instructions: 'Stir-fry mixed vegetables with garlic until tender-crisp.',
    servings: 4,
    cuisineType: 'Mixed' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'cabbage_stir_fry',
    name: 'Stir-Fried Cabbage',
    type: 'veg_side' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["500g cabbage", "4 cloves garlic", "2 tbsp oil", "2 tbsp soy sauce"],
    instructions: 'Stir-fry cabbage with garlic until wilted.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'kangkong_garlic',
    name: 'Kangkong with Garlic',
    type: 'veg_side' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["500g kangkong", "4 cloves garlic", "2 tbsp oil", "2 tbsp soy sauce"],
    instructions: 'Stir-fry kangkong with garlic until tender.',
    servings: 4,
    cuisineType: 'Mixed' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'bok_choy_oyster',
    name: 'Bok Choy with Oyster Sauce',
    type: 'veg_side' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: true,
    ingredients: ["600g bok choy", "3 cloves garlic", "3 tbsp oyster sauce", "2 tbsp oil"],
    instructions: 'Stir-fry bok choy with garlic and oyster sauce.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'asparagus_garlic',
    name: 'Garlic Asparagus',
    type: 'veg_side' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["500g asparagus", "4 cloves garlic", "2 tbsp oil", "1 tbsp soy sauce"],
    instructions: 'Stir-fry asparagus with garlic until tender.',
    servings: 4,
    cuisineType: 'Western' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784881298572,
  },
  {
    id: 'custom_1784883440141',
    name: 'Japanese Curry with Chicken and Potatoes',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Chicken thighs (abt 500g with skin)", "Potatoes (2-3 pcs)", "Carrot-1 (cut rangiri style)", "White onions-1.5 to 2 (diced finely)", "Curry powder/roux", "Worcester sauce - 1 tbsp", "Ketchup - 1 tbsp", "Soy sauce - 1 tbsp", "Honey - 1 tbsp"],
    instructions: 'Make a baking soda solution (1/8 tsp baking soda, 1 tsp salt, ¼ cup water) for caramelizing the onions. Chop onions finely, rangiri-cut the carrots, cube the potatoes slightly larger than the carrots, and grate the ginger and garlic. Trim and cube the chicken, season with salt and pepper. Brown chicken skin-side down in a deep pot with oil, then flip and brown the other side. Add ginger and garlic, fry until fragrant. Add onions and the baking soda solution, cover and cook 10 minutes. Uncover, stir, and boil off the remaining liquid, then add carrots and fry until deep brown (about 15 minutes). Add stock and potatoes, skim off any scum. Cover and simmer 40 minutes to 1 hour until everything is tender, stirring occasionally. Turn off heat and dissolve the curry roux into the pot. Simmer on low 10-15 minutes until thickened. Optionally stir in ketchup, soy sauce, Worcester sauce, and honey for extra flavour, then taste and adjust.',
    servings: 4,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1784883440141,
  },
  {
    id: 'thai_lime_garlic_chilli_fish',
    name: 'Thai Steamed Lime and Garlic Chilli Fish',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["1 whole seabass (~1kg)", "3 big shallots, crushed", "2 stalks lemongrass, crushed", "Coriander, for garnish", "3 small red chillies (for gravy)", "3 small green chillies (for gravy)", "2-3 cloves garlic, sliced/minced (~3 tbsp, for gravy)", "~4 tbsp lime juice (for gravy)", "~5 tsp sugar (for gravy)", "2 tbsp fish sauce (for gravy)"],
    instructions: 'Mix the gravy (chillies, garlic, lime juice, sugar, fish sauce) together, taste test, and set aside. Remove the fish guts and slice lengthwise on both sides for easier eating. Wash thoroughly, rub with salt and lime to remove any fishy smell, rinse well. Score the fish to the bone. Stuff the cavity with the crushed lemongrass and shallots. Steam over boiling water for 13-20 minutes until cooked through. Transfer to a serving plate, pour the gravy over, and garnish with sliced lime, garlic, and coriander.',
    servings: 4,
    cuisineType: 'Thai' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1784992991557,
  },
  {
    id: 'jap_fried_chicken_tenders_negi',
    name: 'Juicy Japanese Fried Chicken Tenders with Spring Onion Dressing',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["600g chicken breast, cut into tenders (tendon removed)", "Salt & pepper", "2 tbsp sake", "2 cloves garlic, minced", "Garlic powder", "Potato starch, for coating", "Dipping sauce:", "3-4 tbsp rice vinegar", "3-4 tbsp soy sauce", "1 tbsp sesame oil", "1.5-2 tbsp sugar", "Chilli oil (rayu), optional", "Shichimi (Japanese chilli mix), a pinch", "2-3 stalks green onion, chopped"],
    instructions: 'Mix all dressing ingredients (rice vinegar, soy sauce, sesame oil, sugar, chilli oil, shichimi, green onions) in a bowl and set aside. Rub salt, pepper, sake, garlic, and garlic powder into the chicken strips, let sit 30 minutes. Coat well with potato starch. Heat oil in a wok to medium heat and fry 4-5 minutes until golden and crispy. Plate and drizzle with the spring onion dressing.',
    servings: 4,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'air_fried_fish_nuggets_tartar',
    name: 'Air Fried Fish Nuggets with Tartar Sauce',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["400g white fish fillet, cut into bite-sized pieces", "Salt, white pepper, garlic powder (marinade)", "Corn flour", "1 egg, beaten", "Panko breadcrumbs", "1 mini cucumber pickle, chopped", "\u00bc white onion, chopped", "\u00bd-1 boiled egg, chopped", "3 tbsp Japanese mayo", "Lemon juice, a dash", "1 tbsp milk (optional)"],
    instructions: 'Cut fish into bite-sized pieces and marinate with salt, black pepper, and garlic powder. Coat in order: corn flour, then beaten egg, then panko breadcrumbs. Line an air fryer with foil and drizzle olive oil top and bottom. Air fry 6 minutes per side until golden and crispy. While waiting, make the tartar sauce by mixing the chopped pickle, onion, boiled egg, mayo, lemon juice, and milk together, adjusting salt to taste.',
    servings: 4,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'salmon_takikomi_gohan',
    name: 'Salmon Takikomi Gohan',
    type: 'rice_noodle_one_pot' as const,
    protein: 'fish' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["\u00bd cup brown rice", "~\u00bd cup water", "1 pc kombu seaweed", "Hijiki seaweed (soaked), a bit", "1-2 pieces salmon, salted", "~4 pcs mushrooms (shiitake/shimeji), sliced", "3-4 slices ginger", "1 tbsp Japanese soy sauce", "Sugar, less than \u00bd tsp", "1 tbsp sake", "Green onions, for topping", "Optional: edamame or tofu pouches, blanched and sliced"],
    instructions: 'Combine rice, water, kombu, hijiki, mushrooms, ginger, soy sauce, sugar, and sake in the rice cooker. Place the salted salmon on top. Cook about 40-45 minutes (rice cooker timing); can steam to reheat. Flake the salmon through the rice and top with green onions before serving.',
    servings: 2,
    cuisineType: 'Japanese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'pad_see_ew',
    name: 'Pad See Ew (Thai Char Kway Teow)',
    type: 'rice_noodle_one_pot' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["A handful of thick kway teow", "2 cloves garlic, chopped", "Kailan (do not substitute a watery veg like cabbage)", "1-2 eggs", "170g protein of choice (beef, chicken, or fish)", "1 tsp oil or sesame oil (marinade)", "1 tbsp light soy sauce (marinade)", "1 tbsp oyster sauce", "1 tsp light soy sauce", "1 tsp Golden Mountain sauce", "1 tsp fish sauce (optional)", "1 tsp dark soy sauce", "1 tsp sugar", "White pepper, a couple dashes"],
    instructions: 'Cook the protein in the wok until 80% done, set aside. Add more oil, then garlic and egg. Add well-drained kailan and stir. Add the kway teow noodles. Add half the sauce and coat the noodles well, letting them sit to char slightly. Add the protein back (don\'t add liquid to the noodles at this point). Add the remaining sauce and stir well.',
    servings: 1,
    cuisineType: 'Thai' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'beef_chow_fun',
    name: 'Beef Chow Fun',
    type: 'rice_noodle_one_pot' as const,
    protein: 'beef' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Beef slices (steamboat-cut, tendon-free)", "Hor fun (medium thick)", "A handful of bean sprouts", "\u00bd white onion, sliced", "2-3 stalks green onion, stems and leaves separated", "1 tsp baking soda (marinade)", "1 tsp cornstarch (marinade)", "1 tsp oyster sauce (marinade)", "1 tsp light soy sauce (marinade)", "1 tsp dark soy sauce (marinade)", "White pepper, a couple dashes (marinade)", "2 tbsp water (marinade)", "1 tsp cooking wine (marinade)", "1 tsp sugar (marinade)", "1 tsp oil (marinade, added last)", "1 tsp dark soy sauce (sauce)", "1 tsp light soy sauce (sauce)", "1 tsp oyster sauce (sauce)"],
    instructions: 'Slice onions and green onions. Rinse beef to remove blood, squeeze dry, and add marinade. Loosen the hor fun. In a heated wok with oil, fry beef until almost cooked, then remove. Wipe the wok, top up oil, add white onion and green onion stems, fry until fragrant. Add hor fun, loosen, and let it char slightly. Add sauce and mix well. Add bean sprouts and green onion leaves. Add beef back and cook until done (about 1 minute). Top with a splash of sesame oil.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'ban_nan_claypot',
    name: 'Ban Nan Claypot',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["8-10 pieces fish belly, sliced", "4-5 slices fried tofu", "2-3 pieces shiitake mushrooms, sliced", "5-6 stalks green onion (ends and stems)", "~10 slices ginger", "~2 cloves garlic, sliced", "~2 cloves shallots, sliced", "1.5 tbsp cornstarch + water", "1.5 tbsp each corn flour, rice flour, glutinous flour (for coating fish)", "\u00bd-1 rice bowl chicken stock", "Sugar, sesame oil, pepper, light soy sauce, Huatiao wine, egg yolk, potato starch (fish marinade)", "1 tsp soy sauce (gravy)", "2 tsp oyster sauce (gravy)"],
    instructions: 'Slice fish into pieces and pat dry. Mix the fish marinade, coat the fish, and marinate about 20 minutes. Slice ginger, onion, and shallots. Fry the tofu and set aside. Coat the fish in the mixed flour. Heat a wok, add ginger slices and fry until fragrant, then fry the fish slices until golden; remove and set aside. In a claypot, add oil and fry the aromatics (green onion stems, shallots, ginger, garlic) lightly. Add the fried fish and gravy to coat. Add chicken broth and starch slurry, stirring to mix. Cover and stew about 3 minutes. Near the end, drizzle half a capful of Huatiao wine on the closed lid. Top with green onion stems and serve hot.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'assorted_veg_casserole_vermicelli_seafood',
    name: 'Assorted Veg Casserole with Vermicelli and Seafood',
    type: 'rice_noodle_one_pot' as const,
    protein: 'seafood' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["3 pcs shiitake mushrooms", "~6 stalks baby broccoli", "4-5 pcs baby nai bai or bok choy, halved", "A small bunch glass vermicelli, soaked", "250ml chicken broth or dashi stock", "Optional: sliced squid, sliced mao gua", "A small handful dried shrimp or dried scallops, soaked (keep the soaking water)", "3-4 cloves garlic, chopped", "1 small piece ginger, sliced", "Green onion stem, a few pieces", "1-1.5 tbsp oyster sauce", "\u00bd tbsp dark soy sauce", "\u00bd tbsp light soy sauce", "\u00bd tsp sugar", "1 tbsp water", "White pepper, 1 dash", "~2 tbsp cornstarch slurry"],
    instructions: 'Cut the veg into bite-sized pieces and soak in salt water about 20 minutes. Soak the vermicelli. Blanch the hard veg in salted water 30 seconds to 1 minute, cool in ice water, and set aside. Mix the seasonings with the stock and the dried shrimp/scallop soaking water. In a claypot, stir-fry the aromatics, mushrooms (and squid, if using) until fragrant. Add the stock and seasonings, cover, and bring to a boil. Add the cornstarch slurry. Add the vermicelli, then the veg, submerging them. Stew covered for about 3 minutes and serve hot.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'ginger_onion_fish',
    name: 'Ginger Onion Fish',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["~150g sheng yu/snakehead fish slices, thin", "Salt, white pepper, Shaoxing wine, cornflour, oil (marinade)", "Tapioca starch, for coating", "2 small pieces ginger, flattened and sliced", "2-3 stalks green onion stems, sliced diagonally", "Green onion leaves, sliced", "2 cloves garlic, chopped", "1 cup water or fish stock", "1 tsp oyster sauce", "1 tsp light soy sauce", "Sugar, ~\u00bd tsp, plus salt", "White pepper", "1 tsp cornstarch solution", "1 tsp Shaoxing wine, to drizzle at the end", "Optional: dark soy sauce"],
    instructions: 'Marinate the fish, mixing by hand, and rest 10 minutes. Either coat in tapioca flour and fry until golden, or blanch in water with 2 slices of ginger and a stalk of green onion until cooked; set aside either way. In a wok, add oil and ginger slices, fry until fragrant and golden. Add garlic and the white part of the green onion. Add water/fish stock, oyster sauce, light soy sauce, white pepper, salt, and sugar, then add the cornstarch solution to thicken. Add the fish back in. Add a little dark soy sauce, drizzle with Shaoxing wine, add the green onion leaves, mix well, and serve hot.',
    servings: 2,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'onion_fried_egg_prawns',
    name: 'Onion Fried Egg with Prawns',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["1 large red onion (or half a large white onion)", "2 eggs", "1 stalk green onion", "Salt / fish sauce, white pepper", "Optional: Huatiao wine", "4-5 small prawns", "1 tsp cornstarch, mixed with a bit of water"],
    instructions: 'Cut the red onion into strips. Cut the green onion into pieces (leaves about 1 inch, stems chopped smaller). Deshell and cut the prawns into smaller pieces. In a hot wok with 1-2 tbsp oil, fry the onions until half cooked, then remove to a bowl. Add all other ingredients to the same bowl and beat the egg in lightly (don\'t overbeat), seasoning with fish sauce and white pepper. In the same wok on medium heat, pour in the egg mixture. Use chopsticks to spread evenly and poke small holes in the middle for even cooking. Flip and cook a few more minutes before stirring, topping up oil as needed. Serve hot.',
    servings: 2,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'garlic_butter_soy_prawns',
    name: 'Garlic Butter Soy Prawns',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["400g prawns, shell-on, deveined", "4-5 cloves garlic, minced", "2 tbsp butter", "1 tbsp light soy sauce", "1 tsp oyster sauce", "\u00bd tsp sugar", "White pepper", "Green onion, sliced, for garnish"],
    instructions: 'Note: not written down in your docs, this is a standard version to verify. Pat the prawns dry and season lightly with white pepper. Melt butter in a hot pan, add garlic, and fry until fragrant but not browned. Add the prawns and fry until just turning pink. Add soy sauce, oyster sauce, and sugar, tossing to coat. Cook until the prawns are just cooked through, being careful not to overcook. Garnish with green onion and serve immediately.',
    servings: 4,
    cuisineType: 'Mixed' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'stir_fried_prawns_garlic',
    name: 'Stir Fried Prawns with Garlic',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["400g prawns, shell-on, deveined", "5-6 cloves garlic, sliced", "1 tbsp light soy sauce", "1 tbsp Shaoxing wine", "White pepper", "Green onion, for garnish"],
    instructions: 'Note: not written down in your docs, this is a standard version to verify. Pat the prawns dry. Heat oil in a wok, fry the garlic until golden and fragrant, and remove half to set aside for garnish. Add the prawns and stir-fry on high heat until they start turning pink. Add soy sauce, Shaoxing wine, and white pepper, tossing to coat. Cook until just done, then top with the reserved fried garlic and green onion.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'thai_garlic_chicken',
    name: 'Thai Garlic Chicken',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["500g chicken breast/thigh", "8 cloves garlic, chopped", "1-2 stalks coriander stem, finely minced", "1 tsp sugar", "1 tbsp oyster sauce (marinade)", "1 tsp Mountain soy sauce (marinade)", "1 tsp Thai light soy sauce (marinade)", "1 tsp Thai fish sauce (marinade)", "1 tsp dark soy sauce, for colour (marinade)", "Black pepper, white pepper (marinade)"],
    instructions: 'Chop the garlic. Slice the chicken and coat with the marinade, mincing the coriander stem into the marinade too. Sprinkle a bit of salt on the chopped garlic. Add ample oil to a cold wok, add the garlic, and cook on low heat until golden brown, then strain the oil (keep it) and let the garlic cool. Using 2 tbsp of the reserved garlic oil, fry the chicken. When almost cooked, add the sugar and mix well. Cook until the marinade dries up, then remove the chicken. Sprinkle with the fried garlic and serve.',
    servings: 2,
    cuisineType: 'Thai' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'sliced_fish_beehoon_soup',
    name: 'Sliced Fish Beehoon Soup',
    type: 'rice_noodle_one_pot' as const,
    protein: 'fish' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Fish slices", "Ginger", "White cabbage", "Tomato slices", "3-4 ladlefuls fish, chicken, or prawn stock", "Fish sauce", "Huatiao wine", "Beehoon", "Sugar, 1 pinch (fish marinade)", "Pepper, 1 pinch (fish marinade)", "Cornstarch/tapioca starch, a bit (fish marinade)"],
    instructions: 'Heat the stock to a rolling boil and skim off any scum. Add ginger and cabbage, then tomato slices. Boil 3-5 minutes on high heat throughout. Add the beehoon. Add fish sauce (about half a tbsp) and Huatiao wine (about 1 capful, to taste). Let the soup return to a rolling boil, then add the fish slices. Optional: add evaporated milk at this point, but cook it at high heat 3-5 minutes first or it\'ll taste overly milky. Taste and adjust fish sauce/Huatiao wine as needed. Top with pepper before serving.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'crispy_noodles_fried',
    name: 'Crispy Noodles (Fried)',
    type: 'rice_noodle_one_pot' as const,
    protein: 'seafood' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["90-100g egg noodles (about one handful)", "2-3 pcs fresh or dried mushrooms", "A few slices squid", "~1 tbsp garlic, minced", "8 pcs medium prawns", "1 leaf Chinese white cabbage", "1 egg", "Spring onions, sliced, for garnish", "Light and dark soy sauce"],
    instructions: 'Soften the egg noodles by pouring tap water over them quickly, without soaking, so they loosen without going soggy; drain. Prepare the veg: slice mushrooms (soak dried ones first), slice cabbage. Prepare the seafood: cook prawns shell-on to preserve texture, then blanch and cool completely; peel after cooling. Slice squid and fish. Season the wok with an oiled kitchen paper rub, then heat with oil. Fry the noodles: heat oil until hot, deep fry the noodles on both sides until crispy, remove and drain. Make the gravy: heat the wok, add oil, garlic, a dash of master stock, and 2-3 ladlefuls of chicken stock, cook until fragrant. Add seafood stock, bring to a boil, add dark soy sauce, then thicken with cornstarch slurry. Add the seafood and veg, let it return to a boil, and thicken further in stages, optionally cracking in a beaten egg at the end. Pour the finished gravy over the crispy noodles and serve.',
    servings: 2,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'seafood_hor_fun',
    name: 'Seafood Hor Fun',
    type: 'rice_noodle_one_pot' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Hor fun noodles", "Light and dark soy sauce", "Seafood of choice"],
    instructions: 'Season the wok with an oiled kitchen paper rub, then heat with cool oil added. Add the hor fun and stir-fry on high heat until lightly browned. Season with light and dark soy sauce (restaurant-style uses only light soy). Set the hor fun aside on a serving plate. Prepare the horfun gravy (same method as Crispy Noodles: garlic, master stock, chicken stock, seafood stock, dark soy sauce, cornstarch slurry) with your seafood added in. Pour the gravy over the hor fun once ready to serve.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'stir_fried_cereal_prawn',
    name: 'Stir-Fried Cereal Prawn',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Medium prawns, shell-on", "1 cube butter", "A small handful curry leaves", "2 chilli padi, sliced", "6 tbsp Nestum cereal (brand-specific)", "Salt, pepper, sugar", "Optional: 1 tbsp Coffeemate, garlic powder", "Cornstarch/multipurpose flour/tapioca flour/potato flour, for coating", "Garlic, chopped"],
    instructions: 'Trim the sharp edges off the prawn heads, legs, and tails; devein by cutting from head to tail; remove the dark \'brain\' in the head. Sprinkle prawns with salt and pepper, chill until ready to use. Slice the chilli padi. Mix the cereal mixture (Nestum, sugar, salt, white pepper, optional Coffeemate/garlic powder) and set aside. Drain and coat the prawns with cornstarch, making sure they\'re dry. Heat oil and fry the prawns until golden brown; remove, discard the oil, and clean the wok. On low heat, add butter, then immediately garlic, curry leaves, and chilli, stir-frying until fragrant, then turn off the heat. Add the cereal mixture and stir with residual heat until slightly sandy and infused with butter, then add the prawns back and stir to coat. Top with cilantro and serve.',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'vietnamese_spring_rolls',
    name: 'Vietnamese Spring Rolls',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["1 egg", "Lettuce, a few pieces", "Basil leaves, 1 stalk", "Morning glory leaves", "Shredded jicama, \u2153 portion", "Shredded carrots, \u2153 portion", "Prawns, ~3-4 per roll", "Sausage, ~4-5 slices", "Rice paper, 2-3 pieces", "Minced shallots, optional (dipping sauce)", "3 tbsp hoisin sauce, per 2 pax (dipping sauce)", "1 tsp peanut butter, per 2 pax (dipping sauce)", "3 tbsp water (dipping sauce)", "1 tbsp coconut milk (dipping sauce)", "Crushed peanuts (dipping sauce)"],
    instructions: 'Slice the jicama and carrots into strips. Devein the prawns, wash, and salt lightly. Boil the prawns until red, then transfer to ice water; once cooled, peel and slice in half. Beat and fry the egg into a thin sheet, roll it up, and slice into thin strips. In the same pan, lightly stir-fry the carrot and jicama strips using residual heat only. Make the dipping sauce by combining all its ingredients in a pot and stirring on medium heat until well mixed. Place the rice paper smooth-side up, use a wet lettuce leaf to soften it on both sides until translucent. Flatten the lettuce stem, layer on basil and morning glory leaves, and roll. Arrange the jicama/carrot mix, egg strips, and sausage next to the roll. Fold in both sides, then roll upward to seal. Serve with the dipping sauce and extra greens.',
    servings: 4,
    cuisineType: 'Vietnamese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'ban_xeo',
    name: 'Ban Xeo (Fried Egg Pancake with Chicken & Prawns)',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["~50g minced chicken (swapped from pork in the original recipe)", "~3 prawns, peeled and deveined", "\u00bd small white onion, sliced", "A small handful mung beans, soaked", "A small handful beansprouts", "1-1.5 tsp shallots, chopped", "Perilla leaf, mustard leaf/lettuce, basil leaves, for wrapping", "~1 tsp fish sauce (marinade)", "~\u00bd tsp sugar (marinade)", "1 tsp black pepper (marinade)", "60g rice flour + 1 tsp turmeric, Ban Xeo flour (batter)", "Spring onions, green part, sliced (batter)", "50ml beer + 100ml water (batter)", "1 tbsp coconut milk (batter)", "4 tsp garlic, minced (dipping sauce)", "Chilli to taste (dipping sauce)", "3 tsp sugar (dipping sauce)", "2 tsp rice vinegar (dipping sauce)", "3 tsp fish sauce (dipping sauce)", "2 tbsp water (dipping sauce)"],
    instructions: 'Note: your source used pork, swapped to chicken to match the household\'s no-pork rule. Mix and taste-test the dipping sauce. Heat a pan with 2-3 swirls of oil. Stir-fry the shallots, minced chicken, and prawns until half-cooked and fragrant, spreading evenly over the pan. Pour about 4 ladles of batter over, swirling to cover everything. Once the batter sets, sprinkle on the beansprouts, mung beans, and sliced onion. Add one more swirl of oil around the edges for crispiness. Cook on low heat about 4 minutes until crispy. Fold in half and serve hot with greens and dipping sauce.',
    servings: 2,
    cuisineType: 'Vietnamese' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'hanoi_fried_spring_rolls',
    name: 'Hanoi Fried Spring Rolls',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["300g minced chicken", "A small handful wood ear mushroom, soaked and finely chopped", "A small handful glass noodles, soaked and chopped", "1 small carrot, grated", "1 shallot, minced", "2 cloves garlic, minced", "1 egg", "Fish sauce, black pepper", "Rice paper or spring roll wrappers", "Lettuce, herbs, and nuoc cham dipping sauce, to serve"],
    instructions: 'Note: not written down in your docs, this is a standard version to verify. Combine minced chicken, mushroom, noodles, carrot, shallot, garlic, egg, fish sauce, and pepper in a bowl and mix well. Wrap tightly in the spring roll wrappers. Deep or shallow fry on medium heat, turning occasionally, until golden and crispy (about 8-10 minutes). Drain on paper towels. Serve wrapped in lettuce and herbs with nuoc cham dipping sauce.',
    servings: 4,
    cuisineType: 'Vietnamese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'bun_ca_sai_gon',
    name: 'Bun Ca Sai Gon (Rice Noodle Fish Soup)',
    type: 'rice_noodle_one_pot' as const,
    protein: 'fish' as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["300g white fish fillet (e.g. batang/mackerel), sliced", "1.5L fish or chicken stock", "2 tomatoes, quartered", "A small handful pineapple, sliced (optional)", "Dill and rice vermicelli", "Fish sauce, sugar, salt to taste", "Garlic and shallots, fried, for garnish", "Bean sprouts, lettuce, herbs, to serve"],
    instructions: 'Note: not written down in your docs, this is a standard version to verify. Bring the stock to a boil and season with fish sauce, sugar, and salt. Add the tomatoes and pineapple (if using), simmer until softened. Add the fish slices and poach gently until just cooked, removing promptly to avoid overcooking. Blanch the rice vermicelli separately and portion into bowls. Ladle the hot broth and fish over the noodles. Top with dill and fried garlic/shallots, and serve with bean sprouts, lettuce, and herbs on the side.',
    servings: 4,
    cuisineType: 'Vietnamese' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'garlic_salmon_mediterranean',
    name: 'Garlic Salmon with Mediterranean Flavours (Air-Fried)',
    type: 'protein_main' as const,
    protein: 'fish' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Salmon fillet(s)", "2 cloves garlic, minced", "Ginger, grated", "White part of green onions, minced", "Black pepper, salt", "2 tsp olive oil (1 tsp in air fryer, 1 tsp drizzled on top)"],
    instructions: 'Defrost the salmon, wash, and pat dry. Season lightly with salt and black pepper. Mix the topping ingredients (garlic, ginger, green onion), seasoning lightly with salt if the slab is thick. Line the air fryer with foil and sprinkle with olive oil. Place the salmon in, top with the aromatics mix, and drizzle with the remaining olive oil for crispiness. Preheat the air fryer, then cook at 190°C for about 12 minutes (4-5 minutes per side, flipping halfway and checking doneness).',
    servings: 4,
    cuisineType: 'Western' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'acqua_pazza_fish',
    name: 'Acqua Pazza Fish',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["150g sea bream", "1 clove garlic, sliced", "1 tbsp olive oil, plus 2-3 tbsp extra to finish", "A bit of butter", "Parsley flakes, a pinch", "~4 clams", "3-4 cherry tomatoes, halved and semi-dried in the oven", "Salt, black pepper", "2 tbsp sake or white wine"],
    instructions: 'Halve the cherry tomatoes and grill in the oven until slightly dried; set aside. Lightly salt the sea bream and add a little black pepper, then pan-fry skin-side down in olive oil and butter until golden. In the same pan on low heat, add more olive oil as needed and fry the sliced garlic and cherry tomatoes until fragrant, then add a little salt and the sake/white wine. Add water to cover about half the fish and bring to a boil on high heat. Add the clams, cover, and cook until they open. Taste the broth and adjust salt. Finish with a generous drizzle of extra virgin olive oil, add chopped parsley, stew about 1 minute, and serve hot.',
    servings: 2,
    cuisineType: 'Western' as const,
    spiceLevel: 'light' as const,
    createdAt: 1785100000000,
  },
  {
    id: 'custom_1785081277844',
    name: 'Wok Hei Bee Hoon with Chicken (Serves 2 pax)',
    type: 'protein_main' as const,
    protein: 'chicken' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Bee hoon \u2013 100g", "Fish cake (slices)", "Prawns \u2013 4-5 pieces (with tail on)", "Lean meat (chicken/ pork)", "Garlic (chopped) \u2013 3-4 cloves", "(Optional) Fish cake (sliced) \u2013 1 piece", "Cabbage/ Chinese cabbage/ Cai Xin \u2013 \u00bc piece, torn to bite-sized pieces", "Oyster sauce \u2013 2 tbsp", "Dark soy sauce- 1 tbsp (adjust later if needed)", "Water/ stock", "Salt (a little)", "Sugar (a little)", "Soy sauce (a little)", "White pepper \u2013 a dash", "Chicken marinade", "Chicken/ Pork slices", "Salt \u2013 1 tsp", "Smashed ginger juice (add hot water to a piece of smashed ginger, and cool)", "Corn starch (add after water and salt are well mixed and absorbed) \u2013 1 tsp", "Oil \u2013 a few drops"],
    instructions: '-	Soak bee hoon in water for about 10 mins, then drain well and set aside. -	Chop garlic & veggies -	Peel prawns & Marinate meat -	In a heated wok, add oil and fry bee hoon till fragrant. Set aside -	Add oil to the wok, add lean meat, followed by chopped garlic -	When fragrant, add veggies and mix well on high heat till fragrant. -	Add 1-2 tbsp oyster sauce, followed by a small drizzle of 1 tbsp of dark soy sauce (can adjust later if colour not right) -	Fry till fragrant first -	Add water/ stock, followed by a dash of salt, a dash of sugar, Soy sauce (a dash) and a dash of white pepper -	Once fragrant, add bee hoon and stew to allow stock to absorb -	Once almost ready, add prawns and steam till stock is absorbed -	If too light, add some dark soy sauce -	Once colour is brown, serve hot.',
    servings: 2,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'medium' as const,
    createdAt: 1785081277844,
  },
  {
    id: 'custom_1785081396420',
    name: 'Claypot Garlic Sauce Prawn Balls with Enoki & Chinese cabbage',
    type: 'protein_main' as const,
    protein: 'seafood' as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Garlic 10-15 cloves, minced and rinse in water. Drain and set aside", "\u2022\tChilli padi 1-2pcs, minced", "\u2022\tWhite spring onion, minced", "\u2022\tVermicelli, 1 bunch, soak in water 20-30 mins, till soft", "\u2022\tChinese cabbage, few stalks", "\u2022\tEnoki mushrooms 1 pkt", "\u2022\tPrawn (approx. 200g), make to paste. Add in little egg white, salt, pepper and sugar. Mix till sticky", "Seasoning (garlic sauce)", "Oyster sauce 1tbsp", "Light soya sauce 1tbsp", "Sugar 1tsp", "MSG 1/2tsp", "Seasoning", "Salt little", "Pepper little"],
    instructions: '1. Heat wok with 2tbsp of oil. Add in 2/3 portion of minced garlic and fry till light golden colour. Add in balance garlic, chilli padi and white spring onion and continue to fry. Then add seasoning and continue to fry for another minute. Set aside 2. Arrange the Chinese cabbage in the claypot, followed by enoki mushrooms. 3. Boil a pot of water till bubbles at the side of the wok are seen, then turn to low heat. Knead the prawn paste into balls and put inside the water one at a time. Once all the prawn balls are in the water, turn to high heat and bring to boil. Immediately scoop up and transfer into a pot of cold water. 4. Put some garlic sauce on top of the enoki mushrooms. Then add on the vermicelli followed by little salt and pepper. Then add some water followed by prawns balls. 5. Lastly add the balance garlic sauce and cover the lid. Cook on high heat and turn to low heat for 3-5min. 6. Serve',
    servings: 4,
    cuisineType: 'Cantonese' as const,
    spiceLevel: 'light-medium' as const,
    createdAt: 1785081396420,
  },
];
