import { Recipe } from './types';

/**
 * User's curated 59 recipes (exported from MakanPlan)
 * This is the source of truth for the app's recipe library
 */
export const USER_RECIPES: Recipe[] = [
  {
    id: "acqua_pazza_fish",
    name: "Acqua Pazza Fish",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["150g sea bream (or cod/ any white fish); 1 clove garlic, sliced; 1 tbsp olive oil, plus 2-3 tbsp extra to finish; A bit of butter; Parsley flakes, a pinch; ~4 clams; 3-4 cherry tomatoes, halved and semi-dried in the oven; Salt, black pepper; 2 tbsp sake or white wine", "(Another recipe - OrsaraRecipes)", "1.5 lbs. Cod Fish Fillets", "1 Shallot thinly sliced", "2 Garlic Cloves chopped", "1 Fennel Bulb thinly sliced", "1 lb. Grape Tomatoes halved", "2 Tbsp. Capers rinsed", "1 tsp. Hot Pepper Flakes", "1 tsp. Sea Salt", "2/3 cups Water", "1/4 cup White Wine dry, like Chardonnay", "Handful Parsley chopped", "Extra Virgin Olive Oil"],
    instructions: "Halve the cherry tomatoes and grill in the oven until slightly dried; set aside. Lightly salt the sea bream and add a little black pepper, then pan-fry skin-side down in olive oil and butter until golden. In the same pan on low heat, add more olive oil as needed and fry the sliced garlic and cherry tomatoes until fragrant, then add a little salt and the sake/white wine. Add water to cover about half the fish and bring to a boil on high heat. Add the clams, cover, and cook until they open. Taste the broth and adjust salt. Finish with a generous drizzle of extra virgin olive oil, add chopped parsley, stew about 1 minute, and serve hot.",
    servings: 2,
    cuisineType: "Western" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "air_fried_fish_nuggets_tartar",
    name: "Air Fried Fish Nuggets with Tartar Sauce (Eat with Hank & Dash of Spices recipe)",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["400g white fish fillet, cut into bite-sized pieces", "Salt, white pepper, garlic powder (marinade)", "Corn flour", "1 egg, beaten", "Panko breadcrumbs", "1 mini cucumber pickle, chopped", "¼ white onion, chopped", "½-1 boiled egg, chopped", "3 tbsp Japanese mayo", "Lemon juice, a dash", "1 tbsp milk (optional)"],
    instructions: "1) Cut fish into bite-sized pieces and marinate with salt, black pepper, and garlic powder. \n2) Coat in order: corn flour, then beaten egg, then panko breadcrumbs. \n3) Line an air fryer with foil and drizzle olive oil top and bottom. \n4) Air fry 6 minutes per side until golden and crispy. \n5) While waiting, make the tartar sauce as below. \n\n(For tartar sauce)\n1) Add some salt to chopped onions, rub and set aside for 5 mins. \n2) Rinse well with water and squeeze dry.\n3) Add chopped pickles, onion, boiled egg, mayo, lemon juice, and milk together, adjusting salt to taste and mix well.",
    servings: 4,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "assorted_veg_casserole_vermicelli_seafood",
    name: "Assorted Veg Casserole with Vermicelli and Seafood",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["3 pcs shiitake mushrooms; ~6 stalks baby broccoli; 4-5 pcs baby nai bai or bok choy, halved; A small bunch glass vermicelli, soaked; 250ml chicken broth or dashi stock;", "(Optional) sliced squid, sliced mao gua;", "(Aromatics) 3-4 cloves garlic, chopped; 1 small piece ginger, sliced; Green onion stem, a few pieces;", "(Seasonings) 1-1.5 tbsp oyster sauce; ½ tbsp dark soy sauce; ½ tbsp light soy sauce; ½ tsp sugar; 1 tbsp water; White pepper, 1 dash; ~2 tbsp cornstarch slurry", "A small handful dried shrimp or dried scallops, soaked (keep the soaking water);"],
    instructions: "Cut the veg into bite-sized pieces and soak in salt water about 20 minutes. \nSoak the vermicelli. \nBlanch the hard veg in salted water 30 seconds to 1 minute, cool in ice water, and set aside. \nMix the seasonings with the stock and the dried shrimp/scallop soaking water. In a claypot, stir-fry the aromatics, mushrooms (and squid, if using) until fragrant. \nAdd the stock and seasonings, cover, and bring to a boil. \nAdd the cornstarch slurry. \nAdd the vermicelli, then the veg, submerging them. \nStew covered for about 3 minutes and serve hot.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "ban_nan_claypot",
    name: "Ban Nan Claypot",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["8-10 pieces fish belly, sliced; 4-5 slices fried tofu; 2-3 pieces shiitake mushrooms, sliced; 5-6 stalks green onion (ends and stems); ~10 slices ginger; ~2 cloves garlic, sliced; ~2 cloves shallots, sliced", "(For coating fish) 1.5 tbsp cornstarch + water; 1.5 tbsp each corn flour, rice flour, glutinous flour ; ½-1 rice bowl chicken stock", "(Fish marinade) Sugar 1/2 tsp, sesame oil 1 tsp, pepper, light soy sauce 1 tbsp, Huatiao wine 1 tbsp, egg yolk 1, potato starch 1 tbsp", "(Gravy) 1 tsp soy sauce; 2 tsp oyster sauce"],
    instructions: "Slice fish into pieces and pat dry. \nMix the fish marinade, coat the fish, and marinate about 20 minutes. \nSlice ginger, onion, and shallots. \nFry the tofu and set aside. \nCoat the fish in the mixed flour. \nHeat a wok, add ginger slices and fry until fragrant, then fry the fish slices until golden; remove and set aside. \nIn a claypot, add oil and fry the aromatics (green onion stems, shallots, ginger, garlic) lightly. \nAdd the fried fish and gravy to coat. Add chicken broth and starch slurry, stirring to mix. \nCover and stew about 3 minutes. \nNear the end, drizzle half a capful of Huatiao wine on the closed lid. Top with green onion stems and serve hot.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "ban_xeo",
    name: "Ban Xeo (Fried Egg Pancake with Chicken & Prawns)",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Minced meat (pork/ chicken) ~ 50gm", "Prawns (peeled & deveined) ~3", "White onions (sliced) - ½ small one", "Mung beans (soaked) – small handful", "Beansprouts (1 small handful)", "Chopped shallots (1-1.5 tsp)", "Veggies (perilla leaf, Mustard leaf/ Lettuce, basil leaves)", "Meat marinade:", "Fish sauce (~1 tsp)", "Sugar (~1/2 tsp)", "Black pepper – 1 tsp", "Batter:", "Ban Xeo flour (60g rice flour + 1 tsp turmeric)", "Spring onions (green part, sliced)", "Beer & water mix (50ml beer + 100 ml water)", "Coconut milk – 1 tbsp", "Dipping sauce:", "Minced garlic – 4 tsp", "Chilli – to taste (half of chilli padi, or half of red chilli)", "Sugar – 3 tsp", "Grind the above in a mortar to release flavour, before adding the next few items!", "Rice Vinegar – 2 tsp", "Fish Sauce – 3 tsp", "Water – 2 tbsp"],
    instructions: "-\tIn a heated pan, add 2-3 swirls of oil (~ 2 tbsp) & ensure pan is well coated with it\n-\tStir fry 1.5 – 2 tsp of chopped shallots, minced meat and 2-3 peeled prawns till half cooked & fragrant. Spread evenly over the pan surface. \n-\tPour ~ 4 ladles of the batter over it and swirl pan till all ingredients are covered (ensure all meat is well-covered! Or else it will burn)\n-\tOnce the batter is set, leave untouched and sprinkle remainder of toppings (beansprouts, mung beans, sliced white onions)\n-\tAdd 1 more swirl of oil around the edges (~1 tbsp) for crispiness\n-\tCook on low heat for ~ 4 mins till batter is crispy\n-\tFold in half and serve hot with greens & dipping sauce",
    servings: 2,
    cuisineType: "Vietnamese" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "beef_chow_fun",
    name: "Beef Chow Fun (Spice N Pans recipe?)",
    type: "rice_noodle_one_pot" as const,
    protein: "beef" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Beef slices (steamboat-cut, tendon-free)", "Hor fun (medium thick)", "A handful of bean sprouts", "½ white onion, sliced", "2-3 stalks green onion, stems and leaves separated", "1 tsp baking soda (marinade)", "1 tsp cornstarch (marinade)", "1 tsp oyster sauce (marinade)", "1 tsp light soy sauce (marinade)", "1 tsp dark soy sauce (marinade)", "White pepper, a couple dashes (marinade)", "2 tbsp water (marinade)", "1 tsp cooking wine (marinade)", "1 tsp sugar (marinade)", "1 tsp oil (marinade, added last)", "1 tsp dark soy sauce (sauce)", "1 tsp light soy sauce (sauce)", "1 tsp oyster sauce (sauce)"],
    instructions: "Slice onions and green onions. Rinse beef to remove blood, squeeze dry, and add marinade. Loosen the hor fun. In a heated wok with oil, fry beef until almost cooked, then remove. Wipe the wok, top up oil, add white onion and green onion stems, fry until fragrant. Add hor fun, loosen, and let it char slightly. Add sauce and mix well. Add bean sprouts and green onion leaves. Add beef back and cook until done (about 1 minute). Top with a splash of sesame oil.",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "bun_ca_sai_gon",
    name: "Bun Ca Sai Gon (Rice Noodle Fish Soup) - Co Ba Binh Durong Youtube",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["1 con cá 1kg  (striped bass fish)", "2 đầu cá hồi / xương cá (salmon fish / fish bone)", "350g chả cá chiên ( fried fish pie)", "350g cá thác lác (knifefish paste)", "300g thơm ( khóm ) (pineapple)", "350g cà chua (tomato)", "Bún 1kg bún (rice noodle)", "GIA VỊ THƠM (Herbal ingredients) :", "2 tép xã (lemon grass)", "3 tép tỏi (garlic)", "4 củ hành tím (shallot)", "10g Gừng (ginger)", "4 tép Hành lá (green onion)", "Tiêu (pepper)", "½ chén Hành tím phi (fried shallot)", "2 tsp Rượu nấu ăn (cooking wine)", "GIA VỊ (SPICES) :", "15g  Muối  ( 1 tbsp ) (salt)", "20g Nước mắm ( 1,5 tbsp ) (fish sauce)", "30g Bột nêm ( 2,5 tbsp ) (seasoning powder)", "50g Đường phèn ( 2,5 tbsp ) (rock sugar)", "8g bột ngọt ( ½ tbsp ) (MSG)", "Rau ăn kèm : Bắp cải – Giá – rau thơm ( Húng cây – díêp cá – quế ) (vegestable)."],
    instructions: "Note: not written down in your docs, this is a standard version to verify. Bring the stock to a boil and season with fish sauce, sugar, and salt. Add the tomatoes and pineapple (if using), simmer until softened. Add the fish slices and poach gently until just cooked, removing promptly to avoid overcooking. Blanch the rice vermicelli separately and portion into bowls. Ladle the hot broth and fish over the noodles. Top with dill and fried garlic/shallots, and serve with bean sprouts, lettuce, and herbs on the side.",
    servings: 4,
    cuisineType: "Vietnamese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "chicken_rice_claypot",
    name: "Chicken Rice Claypot",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Ratio of rice to chicken stock: - must follow exactly!", "150g rice to 175g stock (1 pax)", "200g rice to 240g chicken stock (1.5 servings)", "260g (1.5 cups) to 310g stock", "Thai Jasmine rice (Golden Phoenix brand) – 150g", "Chicken stock – 175g", "Chicken pieces (abt 100-120g)", "Ginger (chopped) – a few slices", "Garlic (chopped) – 1 clove", "Chinese sausage – 1 small piece (abt 1 inch)", "Salted fish (one small slice – about half tablespoon for 1 serving)", "Dried shiitake mushroom – 1-2 piece", "Huatiao wine", "Dark soy sauce", "Master sauce", "Chicken oil (from chicken rice recipe) – 2 tbsp", "Chicken marinade:", "Master sauce – 1-2 tbsp for 1 serving", "Corn starch powder – approx. 1 tbsp for 1 serving", "Pepper – 1 pinch", "Mix thoroughly with hand"],
    instructions: "Wash rice – 1 rinse only and soak for exactly 20 mins\nChinese sausage – wash and remove outer covering, then slice\nRehydrate shiitake mushroom, cut away stalk and cut into half\nChop garlic and ginger into fine bits\nCut salted fish into smaller pieces \n\nPut flavoured oil into claypot and heat on high heat. \nFry salted fish till golden brown, then set aside.\nFry Chinese sausage and mushroom, then set aside.\nFry chicken till not translucent (no need 100% cooked), then set aside. \nRemove excess oil from claypot and leave about 1 tbsp of the hot oil for cooking the remaining items. \nAdd chopped garlic and ginger (careful not to burn it as the flame is on high), give it a quick stir to release fragrance till golden and immediately add rice. Stir fry for a while (30 secs) on lower heat and add chicken stock. Stir and cover the claypot lid, turn on high heat. (It is ok to have a bit of chaotar smell as you want it a bit charred, listen to the cracking of the claypot and open lid to check if you think it might be almost done)-check in 3-4 mins\nOnce the mixture is like a thick porridge consistency (almost dry with holes on d surface), reduce heat and add chicken. Put the lid back on and lower heat slightly. Leave to cook for 20 mins.\nWhen the rice is almost cooked, add Chinese sausage, mushroom and salted fish. Quickly cover claypot back. Monitor the heat and adjust up or down as needed (rice should still be steaming and crackling). \nWhen the 20 mins is almost up, pour ¾ capful of Huatiao wine along the edges of the closed claypot lid. Allow to sit for another 1-2 mins, then turn off heat and serve with dark soy sauce (to taste) and green onions.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "chicken_broccoli_family",
    name: "Chicken with Broccoli (Made with Lau recipe)",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Broccoli", "Chicken breast/thigh — sliced", "(Chicken Marinade)", "Cornstarch — 1 tbsp", "Water — 2 tbsp", "Oyster sauce — 1 tbsp", "White pepper — a dash", "(Aromatics)", "Garlic — 2 cloves, minced", "Green onion — stems (a few pcs)", "Ginger — 2 slices", "Carrot — a few slices (for color)", "[Sauce (Universal Stir-Fry Sauce)]", "Oyster sauce — 1 tbsp", "Light soy sauce — 1 tbsp", "Sugar — 1 tsp", "Cooking wine — 2 tsp", "White pepper — ⅓ tsp", "1 tbsp cornstarch & water slurry"],
    instructions: "1) Marinate chicken with cornstarch, water, salt, and white pepper. \n2) Blanch broccoli in boiling water with oil and salt for 3 mins until almost cooked. \n3) Heat wok with oil on medium heat, shallow fry chicken until 80% done (about 2 mins), then set aside. \n4) Add more oil if needed and fry aromatics (garlic, ginger, green onion whites) until fragrant. \n5) Add broccoli and carrots, stir-fry on high heat for 1-2 mins. \n6) Splash cooking wine on wok sides. \n7) Add back chicken and stir quickly. \n8) Pour in mixed sauce (soy sauce, oyster sauce, salt, sugar, cooking wine, white pepper) while stirring. \n9) Taste test. \n10) Add cornstarch slurry gradually to achieve desired sauce thickness. \n11) Finish with sesame oil for shine before serving.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "custom_1785081396420",
    name: "Claypot Garlic Sauce Prawns with Mushrooms & Chinese cabbage (Spice N Pans recipe)",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Garlic 12-15 cloves, minced and rinse in water. Drain and set aside;  Chilli padi 1-2pcs, minced;  White spring onion, minced;  Vermicelli, 1 bunch, soak in water 20-30 mins, till soft;  Chinese cabbage, few stalks;  Shiitake 2-3 pcs sliced/ Enoki mushrooms 1 pkt;  Prawn (approx. 8 pcs). Devein & Add in little salt, pepper and cornstarch. Mix well; Seasoning (garlic sauce); Oyster sauce 1tbsp; Light soya sauce 1tbsp; Sugar 1tsp; Garlic powder 1/2tsp;", "(Seasonings); Salt little; Pepper little, Dark soy sauce (to taste)", "Water/ soup stock (to fill abt half the claypot)"],
    instructions: "1. Prep prawns, vermicelli and veg.\n2. Heat frying pan with 2tbsp of oil. Add in 2/3 portion of minced garlic and fry till light golden colour and fragrant. \nAdd in balance garlic, chilli padi and white spring onion and continue to fry. \nTurn off heat, then add seasonings and continue to fry for another minute on low heat. Set aside \n3. Arrange the Chinese cabbage in the claypot, followed by mushrooms. \n4. Put some garlic sauce on top of the mushrooms. Then add on the vermicelli followed by little salt and pepper. Then add some water/ stock.\n5. Cover the lid. Cook on high heat and turn to low heat for 3-5min. \n6. Add prawns top with the remaining garlic sauce. Steam till prawns are cooked (abt 4-5 mins)\n6. Top with green onions and serve hot. Consume prawns within 5 mins for best texture.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "crispy_noodles_fried",
    name: "Crispy Noodles (Fried) - At Sunrice recipe",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Egg noodles – 90-100g (abt one handful)", "Fresh/ dried mushrooms (either fresh white mushrooms or dried shiitake mushrooms) – 2-3 pieces", "Squid – a few slices", "Minced garlic – 1 piece (approx. 1 tablesppon)", "Medium-sized Prawns (8 pcs)", "Chinese white cabbage – 1 leaf", "Egg -1", "Spring onions (for garnish) - sliced", "Light and dark soy sauce", "Seasoning:", "2 Tbsp Oil for cooking", "1 tsp Dark soya sauce", "1 tsp Oyster sauce", "1 tsp Sesame oil", "1 cup Seafood stock", "⅓ tsp White pepper", "Thickening (cornstarch slurry):", "2 Tbsp Cornstarch", "2 Tbsp Water"],
    instructions: "1) Soften egg noodles by pouring tap water quickly over it and drain with colander (don’t soak as noodles will become too soggy!) It should become loose and detangles but still firm texture\n2) Prepare veg (slice fresh mushrooms (soak and slice dried mushrooms), slice veg\n3) Prepare seafood (fish, prawns, squid) \n- Cook prawns with shell on to preserve size and texture!\n- Boil without cutting, then blanch in either iced water to cool completely or rinse in tap water several times until cool (cannot be lukewarm as it will spoil!) – need to store in freezer, if chiller then only lasts 1-2 days max\n- Remove prawn shells and head after cooling\n- Slice squid and fish (remove fish skin, do not use)\n\n(To season wok):\n- Dip kitchen paper in oil and rub over the wok surface\n- Turn on heat, add oil to wok\n\n(Fry noodles):\n- Heat oil till hot and deep fry egg noodles on both sides till crispy\n- Remove noodles with draining ladle on a plate\n\n(Horfun prep):\n- Turn on flame to high. In a heated wok, add 2 tbsp of room-temp oil. When the oil is hot (can see smoke), add horfun and stir fry till slightly charred. \n- Add light soy sauce (Chinese restaurant), if you want can add some black soy sauce also (hawker style).\n- When nicely & evenly browned, remove horfun on plate.\n\n(Gravy for crispy noodles/ Horfun gravy (same method):\n- Heat wok\n- Add oil, chopped garlic and a dash of master stock, and 2-3 ladlefuls of chicken stock (for 1 portion)and cook till fragrant. \n- Add seafood stock and bring to a boil\n- Add dark soy sauce & wait for stock to boil (bubbling)\n- Add cornstarch slurry to thicken\n- Taste test and adjust as needed (e.g. add master sauce/ dark soy sauce)\n- Can add Huatiao wine at the sides of the wok for more fragrance\n- Add in ingredients (seafood veg, etc)\n- Wait for stock to boil (2nd time)\n- Add more cornstarch slurry gradually in phases while stirring (approx. 2 tbsp at a time)\n- Can add 1 beaten egg at this point if you want (Turn off heat first – dun overcook)\n- Pour final mixture onto crispy noodles/ horfun and serve",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "garlic_salmon_mediterranean",
    name: "Garlic Salmon with Mediterranean Flavours (Air-Fried)",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Salmon fillet(s);", "2 cloves garlic, minced;", "Ginger, grated;", "White part of green onions, minced;", "Black pepper,", "Salt;", "1 tsp olive oil (1/2 tsp in air fryer, 1/2 tsp drizzled on top)"],
    instructions: "1) Defrost the salmon, wash, and pat dry. \n2) Season lightly with salt and black pepper. \n3) Mix the topping ingredients (garlic, ginger, green onion), seasoning lightly with more salt if the slab is thick. \n4) Line the air fryer with foil and sprinkle with olive oil. \n5) Place the salmon in, top with the aromatics mix, and drizzle with the remaining olive oil for crispiness. \n6) Preheat the air fryer, then cook at 190°C for about 12 minutes (~5 minutes per side (depending on thickness of fish), flipping halfway and checking doneness).",
    servings: 1,
    cuisineType: "Western" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "salmon_rice_onepot_family",
    name: "Garlic Soy Salmon and Cabbage One-Pot Rice (Japanese Cooking Channel)",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ["3-4 cloves garlic, chopped;", "Salt to taste;", "400g salmon (ideally more fatty part), cut into slices;", "¼ cabbage, sliced into triangles;", "1 cups rice;", "2-3 mushrooms, sliced;", "1 tsp oil (for frying veg & mushrooms)", "(Gravy)", "5 tsp soy sauce;", "1 tbsp sake;", "2-3 tsp sugar;"],
    instructions: "1) Cook rice in rice cooker with sake. \n2) Chop garlic and set aside 1 clove for vegetables. \n3) Slice cabbage and mushrooms into bite-sized pieces. \n4) Slice salmon into bite-sized pieces. \n5) Make sauce by combining 3 cloves chopped garlic, 2 tsp sugar, and 5 tsp soy sauce. \n6) In a pan, add oil and 1 clove garlic, heat until fragrant. \n7) Add mushrooms and cabbage with a dash of salt and water. \n8) Cook until done and set aside. \n9) In the same pan, add salmon skin-side down (no oil needed). \n10) When half cooked, add sauce and cook until done. \n11) Place vegetables and salmon on top of rice and serve hot.",
    servings: 3,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "ginger_onion_fish",
    name: "Ginger Onion Fish (Mr Hong Kitchen recipe)",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["1. Sheng Yu Fish fillet ~150g marinate with little salt, pepper and shao xing wine. Rub well and add little corn starch and mix well. Lastly add little oil and mix well. Set aside", "2. Ginger 2 small pcs, smashed and cut smaller", "3. Garlic 2 cloves, chopped", "4. White spring onion 2 stalks, cut diagonally slice", "5. Green spring onion 2 stalks, cut 2cm long", "Seasoning", "1. Oyster sauce 1tsp", "2. Light soya sauce 1tsp", "3. Salt little", "4. Sugar little", "5. Pepper little", "6. Potato starch solution", "7. Dark soya sauce little (Optional)", "1 tsp Shaoxing wine, to drizzle at the end"],
    instructions: "1) Marinate the fish, mixing by hand, and rest 10 minutes. \n2) Either coat in tapioca flour and fry until golden, or blanch in water with 2 slices of ginger and a stalk of green onion until cooked; set aside either way. \n3) In a wok, add oil and ginger slices, fry until fragrant and golden. \n4) Add garlic and the white part of the green onion. \n5) Add water/fish stock, oyster sauce, light soy sauce, white pepper, salt, and sugar, then add the cornstarch solution to thicken. \n6) Add the fish back in. \n7) Add a little dark soy sauce, drizzle with Shaoxing wine, add the green onion leaves, mix well, and serve hot.",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "custom_1784883440141",
    name: "Japanese Curry with Chicken, Potatoes, Carrots and Onions (No recipes & Just One Cookbook recipe)",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Chicken thighs (abt 500g with skin)", "Potatoes, medium sized (2-3 pcs)", "Carrot-1 (cut rangiri style)", "White onions- 2 (1.5 - diced finely, 0.5 - cut to thin slices)", "Garlic - 2 cloves, grated", "Ginger - 1 small piece, grated", "Curry powder/roux - 3-4 cubes", "Worcester sauce - 1 tbsp", "Ketchup - 1 tbsp", "Soy sauce - 1 tbsp", "Honey - 1 tbsp", "Sake - 1 tbsp", "Water - 3-4 cups (JP rice cup measurement)", "1/2 tsp baking soda", "1 tsp salt", "a small saucer of water"],
    instructions: "1) Make a baking soda solution (1/8 tsp baking soda, 1 tsp salt, ¼ cup water) for caramelizing the onions. \n2) Chop 1.5 onions finely, rangiri-cut the carrots, cube the potatoes slightly larger than the carrots. Steam in a rice cooker for about 10 mins till half cooked\n3) Grate the ginger and garlic. \n4) Trim and cube the chicken, season with salt and pepper. \n5) Brown chicken skin-side down in a deep pot with oil, then flip and brown the other side. Set aside\n6) Top up some oil if needed, add ginger and garlic, fry until fragrant. \n7) Add chopped onions and the baking soda solution, cover and cook 10 minutes. \n8) Uncover, stir, and boil off the remaining liquid, then add carrots and sliced onions, and fry until deep brown (about 15 minutes). Add stock and potatoes, skim off any scum. \n9) Cover and simmer 40 minutes to 1 hour until everything is tender, checking every 10 mins or so to stir occasionally. \n10) Turn off heat and dissolve the curry roux into the pot. Simmer on low 10-15 minutes until thickened. \n11) Optionally stir in sake, ketchup, soy sauce, Worcester sauce, and honey for extra flavour, then taste and adjust.",
    servings: 4,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "jap_fried_chicken_tenders_negi",
    name: "Juicy Japanese Fried Chicken Tenders with Spring Onion Dressing (Tokyo Kitchen recipe)",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["600g chicken breast, cut into tenders (tendon removed)", "Salt & pepper", "2 tbsp sake", "2 cloves garlic, minced", "Garlic powder", "Potato starch, for coating", "Dipping sauce:", "3-4 tbsp rice vinegar", "3-4 tbsp soy sauce", "1 tbsp sesame oil", "1.5-2 tbsp sugar", "Chilli oil (rayu), optional", "Shichimi (Japanese chilli mix), a pinch", "2-3 stalks green onion, chopped"],
    instructions: "1) Mix all dressing ingredients (rice vinegar, soy sauce, sesame oil, sugar, chilli oil, shichimi, green onions) in a bowl and set aside. \n2) Rub salt, pepper, sake, garlic, and garlic powder into the chicken strips, let sit for at least 30 minutes. \n3) Coat well with potato starch. \n4) Heat oil in a wok to medium heat and fry 4-5 minutes until golden and crispy. \n5) Plate and drizzle with the spring onion dressing.",
    servings: 4,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "tofu_mapo",
    name: "Mapo Tofu",
    type: "protein_main" as const,
    protein: "tofu" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Chicken meat – 1 small piece", "Tofu – 1 slab", "Garlic – 1–2 pcs", "Green onion – 1 sprig", "Marinade for chicken:", "Oyster sauce – 1 tbsp", "Cornflour – 1 tbsp", "Water – 2 tbsp", "Sauce:", "Chilli Toban sauce (doubanjiang) – 2 spoonfuls", "Dark soy sauce – ½ tsp", "Oyster sauce – 1 tbsp", "Sugar – 1 tsp", "Cornstarch solution:", "1 cup water", "Sesame oil – 1 tsp"],
    instructions: "1) Marinate chicken\n2) Cut tofu\n3) Make sauce\n4) Fry aromatics, add chicken, add gravy + cornstarch slurry and tofu\n5) Simmer tofu and chicken till cooked",
    servings: 4,
    cuisineType: "Mixed" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "mixed_veg_stir_fry",
    name: "Mixed Vegetable Stir-Fry (Thai)",
    type: "veg_side" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Gai Lan veg (separate stems and leaves)", "Broccoli/ cauliflower (cut to small florets for easier cooking!)", "Cabbage", "Carrots", "Mushrooms", "Bird’s eye chilli – 2-3 pcs (keep whole, smashed)", "Sliced/ Chopped garlic – 5 cloves", "Water", "Sauce (mix first):", "1 tbsp oyster sauce", "1 tbsp Healthy Boy soy sauce", "1 tbsp Golden Mountain sauce/ 1 tbsp fish sauce", "~ 2 tbsp water", "1.5 tsp sugar"],
    instructions: "1) Boil hard veggies in water for 1 min first. Drain & set aside.\n2) Add oil, then garlic and (optional) chillies into a wok with some oil. Turn on high heat. \n3) When can smell garlic, add hard veg first (add just a bit of water if too hot) – carrots, cauliflower, stem of gai lan\n4) Add cabbage, mushrooms\n5) Add sauce and a bit of water\n6) Add leafy greens then cook on med- high heat till cooked.",
    servings: 4,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "onion_fried_egg_prawns",
    name: "Thai style Fried Egg Omelette with Prawns (Fitous Kitchen recipe)",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["2 eggs (at room temp!) – beat well", "Mountain soy sauce/ Thai fish sauce – 1 tbsp", "Chicken powder/ garlic powder – ½ tbsp", "Lime juice/ water – ½ tbsp", "(Optional) White pepper – a dash", "Any other ingredients (e.g. sliced red onions/ shallots, prawns, basil leaves, minced pork, crab meat)", "(Dipping sauce)", "Lime juice – ½ a lime", "Fish sauce – 2 tbsp", "Small chilli – 2pcs (sliced)", "Garlic – 1 clove (sliced)", "Red onion (sliced) – 1/3", "Sugar – 1/2 tsp"],
    instructions: "1) In medium heat with more oil in a wok (test by dripping a bit of egg in and see if it floats up immediately), pour egg mixture and spread out evenly\n2) When browned on one side, flip and fry till golden. Serve hot",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "pad_see_ew",
    name: "Pad See Ew (Thai Char Kway Teow) - Pailin's Kitchen",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Fresh wide rice noodles", "Protein of your choice, thinly sliced", "Soy sauce for marinating the meat, omit if using shrimp which do not need to be marinated.", "Vegetable oil", "Garlic, chopped", "1 Egg", "Kai Lan (or other leafy green veg)", "Sugar", "Ground white pepper", "Prik Nam Som (Thai chilli vinegar)", "Sauce:", "Oyster sauce", "Thai Soy sauce (Healthy Boy Brand)", "Fish sauce", "Golden Mountain sauce", "Thai Black Soy Sauce (tends to be sweeter) - if using Chinese dark soy sauce, omit Golden Mountain sauce)"],
    instructions: "1) If using chicken, pork, or beef, marinate the meat with soy sauce and a bit of sugar. If your meat is lean, like chicken breast of pork loin, you can add about 2 teaspoons of water to give it extra juiciness. Stir to mix well and let sit while you prep other things.\n2) Combine all sauce ingredients together and stir to mix.\n3) Cut thicker part of the stems of chinese broccoli into thin slices on a diagonal. Roughly chop thinner stems and leaves.\n4) Heat the oil in a well-seasoned wok or a large cast-iron skillet over high heat. Once very hot, add all of the protein and spread it out into a single layer as much as possible. Let the protein sear without moving until the underside is browned and the meat is at least halfway cooked.\n5) Once the meat is browned, toss until the meat is fully cooked. Remove from pan and set aside. If there is meat juices left in the wok, wipe it with a paper towel.\n6) From this step onward, I recommend cooking 1 portion at a time for best results, so before cooking, divide up your ingredients into single portions. Heat the wok over medium high heat then add a little oil and 1 portion of the garlic; sauté until the smallest bits of garlic starts to turn golden.\n7) Add 1 egg and scramble briefly.\n8) Add 1 portion of the Chinese broccoli and toss to coat it evenly in the oil, about 10–15 seconds.\n9) Add 1 portion of the noodles (8oz/225g), 1 portion of the sauce (2 tablespoon + 1 tsp/35 ml) , and 2 teaspoon (10 ml) of sugar. Turn the heat up to high and toss to coat the noodles evenly in the sauce.\n10) Spread the noodles out and let them sit without stirring for about 15-30 seconds until some of the noodles have charred on the underside.\n11) Flip or toss the noodles and let them sit again to further toast the noodles. Repeat the tossing and toasting 1-2 more times.\n12) Add 1 portion of the cooked protein back in without adding any meat juices that has accumulated in the bowl, and toss briefly to mix. Plate and enjoy with white pepper and chili vinegar.",
    servings: 1,
    cuisineType: "Thai" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "salmon_takikomi_gohan",
    name: "Salmon Takikomi Gohan",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["½ cup brown rice;", "~½ cup water;", "1 pc kombu seaweed;", "Hijiki seaweed (soaked), a bit;", "1-2 pieces salmon, salted;", "~4 pcs mushrooms (shiitake/shimeji), sliced;", "3-4 slices ginger;", "1 tbsp Japanese soy sauce;", "Sugar, less than ½ tsp;", "1 tbsp sake;", "Green onions, for topping;", "Optional: edamame or tofu pouches, blanched and sliced"],
    instructions: "1) Combine rice, water, kombu, hijiki, mushrooms, ginger, soy sauce, sugar, and sake in the rice cooker. \n2) Place the salted salmon on top. \n3) Cook about 40-45 minutes (rice cooker timing); can steam to reheat. \n4) Flake the salmon through the rice and top with green onions before serving.",
    servings: 2,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "salmon_foil_family",
    name: "Salmon in Aluminium Foil",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["2 salmon fillets (240g);", "Salt and black pepper to taste;", "½ onion;", "5cm carrot;", "50g shimeji mushrooms;", "2 shiitake mushrooms;", "2 green onion strands;", "1½ tbsp unsalted butter;", "1 tbsp sake;", "2 tbsp soy sauce or ponzu"],
    instructions: "1) Preheat oven to 400°F (200°C). \n2) Prepare foil packets by placing salmon fillets on center of foil. \n3) Season with salt and pepper. \n4) Slice onion, carrot, and mushrooms. \n5) Arrange vegetables around salmon. \n6) Top each fillet with butter and sake. \n7) Drizzle with soy sauce or ponzu. \n8) Fold foil to create sealed packets. \n9) Bake for 12-15 minutes until salmon is cooked through. \n10) Carefully open foil (watch for steam) and serve hot with green onions on top.",
    servings: 2,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "seafood_hor_fun",
    name: "Seafood Hor Fun",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Hor fun noodles;", "Seafood of choice (Fish, prawns, chicken)", "Garlic (chopped)", "Ginger (sliced)", "Veg (Xiao Bai Cai)", "Master sauce", "Chicken stock", "Egg (optional)", "Cornstarch slurry", "Seasonings:", "Dark soy sauce (optional)", "Sesame oil"],
    instructions: "Season the wok with an oiled kitchen paper rub, then heat with cool oil added. Add the hor fun and stir-fry on high heat until lightly browned. \nSeason with light and dark soy sauce (restaurant-style uses only light soy). \nSet the hor fun aside on a serving plate.\nStir fry ginger and garlic till fragrant, then add seafood, followed by chicken stock.\nAdd seasonings and thicken with corn starch, then add in beaten egg (optional).\nPrepare the horfun gravy (same method as Crispy Noodles: garlic, master stock, chicken stock, seafood stock, dark soy sauce, cornstarch slurry) with your seafood added in. \nPour the gravy over the hor fun once ready to serve.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "sliced_fish_beehoon_soup",
    name: "Sliced Fish Beehoon Soup",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Fish slices;", "Beehoon;", "Ginger;", "White cabbage;", "Tomato slices;", "3-4 ladlefuls fish, chicken, or prawn stock;", "Fish sauce;", "(Fish Marinade)", "Fish sauce", "Huatiao wine;", "Sugar, 1 pinch", "Pepper, 1 pinch", "Cornstarch/tapioca starch, a bit", "(Fish stock)", "In Hot oil – add old ginger slices and fry fish bones (e.g. sheng yu) on both sides till fragrant. Can add leek/ spring onion stem/ huatiao wine as desired.", "Prepare hot boiling water - must be boiling hot (bubbling vigorously)!", "Fish bones must be boiling hot too", "Combine boiling hot water and fish bones to create white collagen stock!", "Allow to cool and store in containers in the fridge for future use (can portion it out)"],
    instructions: "1.  Heat stock till boiling (bubbling hot)\n2. Remove scum (if any)\n3. Add ginger and veg (Chinese cabbage) \n4. Add tomato slices\n5.Cook for 3-5 mins at a boil (keep a high flame at all times)\n6. Add beehoon\n7. Add fish sauce (half tbsp), Huatiao sauce (to taste - add around 1 capful)\n8. Allow soup to boil (bubbling hot) first\n9. Then add fish slices\n10. If you want to add milk, add at this point.\n11. Note: Evaporated milk needs to be broken – i.e. cooked at high heat for 3-5 mins before serving! (otherwise will have overly milky taste)\n12. Taste test, if not enough add fish sauce & Huatiao sauce to adjust\n13. Top with pepper before serving.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "cabbage_stir_fry",
    name: "Stir-Fried Cabbage",
    type: "veg_side" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["500g cabbage;", "4 cloves garlic;", "2 tbsp oil;", "2 tbsp soy sauce"],
    instructions: "Stir-fry cabbage with garlic until wilted.",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "stir_fried_cereal_prawn",
    name: "Stir-Fried Cereal Prawn (At Sunrice recipe)",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Medium-sized Prawns (with shell)", "Butter – 1 cube", "Curry leaves – 1 small handful", "Chilli padi (2 pcs) – sliced", "Cereal (use Nestum brand only!)", "Salt", "Pepper", "Sugar", "Coffeemate (optional)", "Garlic powder (optional)", "Cornstarch/ Sunshine multipurpose flour/ Tapioca flour/ Potato flour – for coating prawns", "Chopped garlic", "(Cereal mixture):", "Mix 6 tablespoons of Nestum cereal, 1 tablespoon of sugar, a pinch of salt, a pinch of white pepper", "(Optional) Coffeemate/ garlic powder – 1 tablespoon"],
    instructions: "1) Use scissors to trim off the sharp edges along the top of the prawn head, legs, pointed ‘sting’ on the tail. Devein the prawn by cutting from the end of the head to the tail and removing the dark vein. Also remove the dark ‘brain’ in the middle of the prawn head (as it is toxic).\n2) Sprinkle with salt and pepper, and set aside in chiller until ready to use\n3) Cut chilli padi\n4) Prepare cereal mixture, mix well and set aside\n5) Drain & Coat prawns with cornstarch before frying (should be dry or it’ll splatter the oil!)\n6) Add oil to wok and heat till hot (shallow fry or deep fry also ok). \n7) Single or Double-fry the prawns till golden brown. Set aside and throw away oil. Clean wok. \n\n8) On low fire, add butter. Immediately add chopped garlic, curry leaves and chilli and stir fry till fragrant. Turn off heat when fragrant. \n9) Add cereal mixture, mix well. Continue to stir the mixture using residual heat until slightly sandy texture and infused with the butter. Add back the prawns and stir.\n10) If the cereal is still too dry, can turn on the heat for a few seconds and stir again with residual heat. \n11) Top with cilantro and serve",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_chicken_basil",
    name: "Thai Chicken with Holy Basil (Pad Kra Pow Gai) - Home Cooking with Somjit",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["300g of minced chicken breast", "5 cloves of garlic", "1 bunch of Thai sweet basil leaves, washed and cleaned", "3 pieces of red bird’s eye chilli and large chilli (mix) - adjust spice level as needed", "Onion - half", "Long bean - 1 pc (cut small)", "Sauce:", "Soy sauce - 1 tbsp", "Oyster sauce - 1 tbsp", "Fish sauce - 2 tsp", "Dark soy sauce - 1.5 tbsp", "Sugar - 1.5 tsp", "Water 2 tbsp"],
    instructions: "Pound chopped chillies (large & small) and garlic\nMake sauce\nGrind chicken finely\nCut onions and long beans\nStir-fry garlic and chilli paste with cool oil till fragrant\nAdd chicken, stir well\nAdd vegetables\nAdd sauce, cook till done\nTurn off heat, add basil",
    servings: 4,
    cuisineType: "Thai" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_garlic_chicken",
    name: "Thai Garlic Chicken",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["300 grams chicken breast/ pork loin, cut in to thin bite sized pieces", "5 garlic cloves, chopped fine with peel for make crispy fried garlic", "(Chicken Marinade) 5 coriander roots, 5 garlic cloves,1 tsp white pepper corns. Crushed everything together until fine.", "1 tbsp fish sauce", "1 tbsp soy sauce", "1 tbsp oyster sauce", "¼ tsp baking soda", "2 tsp sugar", "½ cup chopped cilantro"],
    instructions: "1) Chop the garlic. \n2) Slice the chicken and coat with the marinade, mincing the coriander stem into the marinade too. \n3) Sprinkle a bit of salt on the chopped garlic. \n4) Add ample oil to a cold wok, add the garlic, and cook on low heat until golden brown, then strain the oil (keep it) and let the garlic cool. \n5) Using 2 tbsp of the reserved garlic oil, fry the chicken. \n6) When almost cooked, add the sugar and mix well. \n7) Cook until the marinade dries up, then remove the chicken. \n8) Sprinkle with the fried garlic and serve.",
    servings: 2,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_lime_garlic_chilli_fish",
    name: "Thai Steamed Lime and Garlic Chilli Fish",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["1 whole seabass (~1kg);", "3 big shallots, crushed;", "2 stalks lemongrass, crushed;", "Coriander, for garnish;", "3 small red chillies (for gravy);", "3 small green chillies (for gravy);", "2-3 cloves garlic, sliced/minced (~3 tbsp, for gravy);", "~4 tbsp lime juice (for gravy);", "~5 tsp sugar (for gravy);", "2 tbsp fish sauce (for gravy)"],
    instructions: "1) Mix the gravy (chillies, garlic, lime juice, sugar, fish sauce) together, taste test, and set aside. \n2) Remove the fish guts and slice lengthwise on both sides for easier eating. Wash thoroughly, rub with salt and lime to remove any fishy smell, rinse well. Score the fish to the bone. \n3) Stuff the cavity with the crushed lemongrass and shallots. \n4) Steam over boiling water for 13-20 minutes until cooked through. \n5) Transfer to a serving plate, pour the gravy over, and garnish with sliced lime, garlic, and coriander.",
    servings: 3,
    cuisineType: "Thai" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "three_cup_chicken_family",
    name: "Three-Cup Chicken Claypot (Spice N Pans recipe)",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Chicken — 2 thighs/breast (with skin) or wings", "Basil — 1 stalk", "Ginger (thin slices) — 7–8 slices", "Dried red chilli — 2 pcs", "Green onion — 3–4 stalks (separate stems & leaves)", "Garlic — 10–15 cloves, sliced", "Shallots — 4 pcs", "(Gravy)", "Rice wine —  6 tbsp", "Dark soy sauce — 3  tbsp", "Light soy sauce — 3 tbsp", "Sesame oil — 2 tbsp", "Huatiao wine — 1 tbsp (½ cup-full) — drizzle over claypot", "Sugar: 1 big tbsp (2 mini pkts)", "(Chicken marinade): Salt, Pepper, Cornflour, Water"],
    instructions: "1) Put oil in heated wok, add ginger, shallots, garlic & fry till fragrant. \n2) Add red chilli and green onion stems a bit later.\n3) Add chicken & fry till golden brown. Keep aromatics on top to prevent shrinkage/burning. Brown both sides of chicken.\n4) Make a hole in the middle & add sugar. \n5) Caramelize chicken, add ½ of the gravy to cook. Stir till caramelized.\n6) Heat a claypot & transfer ingredients over. \n7) Add basil & remaining gravy. Cover claypot.\n8) Drizzle with 1 tbsp Shaoxing wine.\n9) Stew for 3–4 mins on low heat. Stir once to ensure even coating of gravy. \n10) Serve with green onion stalks (the leaves).",
    servings: 4,
    cuisineType: "Taiwanese" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "vietnamese_spring_rolls",
    name: "Vietnamese Spring Rolls",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Dipping sauce:", "Minced shallots (optional) – stir fry lightly till fragrant first before adding other ingredients below:", "Hoisin sauce – 3 tbsp for 2 pax", "Peanut butter – 1 tsp for 2 pax)", "Water – 3 tbsps", "Coconut milk – 1 tbsp", "Crushed peanuts", "Veggies & other ingredients:", "Egg - 1", "Lettuce – a few pieces", "Basil leaves – 1 stalk", "Morning glory leaves", "Shredded gicama (1/3)", "Shredded carrots (1/3)", "Prawns - ~ 3-4 per roll", "Sausage - ~ 4-5 slices", "Rice paper (dry) – 2-3 pieces", "Water", "Salt"],
    instructions: "-\tSlice gicama & carrots into strips (like popiah filling style)\n-\tRemove head from prawn and devein by using a toothpick/ skewer to pick it out near the tail. Wash prawns & rinse\n-\tCoat lightly with salt\n-\tIn a pot of boiling water, cook prawns till red and place in a bowl of ice water to keep crispy\n-\tAfter shrimp has cooled, peel shell and slice in half\n-\tBeat egg up\n-\tIn a heated pan with oil, fry beaten egg. Cook till done and roll up. Slice the rolled egg into thin strips. \n-\tUsing the same cooking pan, stri fry carrot & gicama strips lightly using only residual heat from the pan.\n-\tMake dipping sauce (combine all ingredients in a pot & stir on medium heat till well mixed). Set aside and top with chillies or chopped peanuts as needed)\n-\tPlace smooth side of rice paper on a plate, with smooth side facing upwards.\n-\tRoll 1 lettuce leaf to make a brush, dip into water and shake of excess water.\n-\tRub the dry rice paper on both sides with the wet lettuce till the rice paper softens slightly and turns transparent. Try to control amount of moisture as it can’t be too wet or dry!\n-\tFlatten lettuce stem by using palm to squash it. Follow by adding 1 perilla leaf, 3-4 leaves of basil, morning glory leaves on top and arrange evenly. Roll veg mix and place on the rice paper. \n-\tArrange gicama and carrot mix next to rolled lettuce, followed by egg rolls and sausage\n-\tFold in both sides of the roll carefully, then roll upwards to finish\n-\tServe with dipping sauce & greens",
    servings: 4,
    cuisineType: "Vietnamese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "custom_1785081277844",
    name: "Wok Hei Bee Hoon with Chicken (Serves 2 pax) - Mr Hong recipe",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Bee hoon – 100g", "Fish cake (slices)", "Prawns – 4-5 pieces (with tail on)", "Lean meat (chicken/ pork)", "Garlic (chopped) – 3-4 cloves", "(Optional) Fish cake (sliced) – 1 piece", "Cabbage/ Chinese cabbage/ Cai Xin – ¼ piece, torn to bite-sized pieces", "Oyster sauce – 2 tbsp", "Dark soy sauce- 1 tbsp (adjust later if needed)", "Water/ stock", "Salt (a little)", "Sugar (a little)", "Soy sauce (a little)", "White pepper – a dash", "Chicken marinade", "Chicken/ Pork slices", "Salt – 1 tsp", "Smashed ginger juice (add hot water to a piece of smashed ginger, and cool)", "Corn starch (add after water and salt are well mixed and absorbed) – 1 tsp", "Oil – a few drops"],
    instructions: "-Soak bee hoon in water for about 10 mins, then drain well and set aside. \n-Chop garlic & veggies \n-Peel prawns & Marinate meat \n-In a heated wok, add oil and fry bee hoon till fragrant. Set aside\n -Add oil to the wok, add lean meat, followed by chopped garlic \n-When fragrant, add veggies and mix well on high heat till fragrant. \n-Add 1-2 tbsp oyster sauce, followed by a small drizzle of 1 tbsp of dark soy sauce (can adjust later if colour not right) \n-Fry till fragrant first \n-Add water/ stock, followed by a dash of salt, a dash of sugar, Soy sauce (a dash) and a dash of white pepper \n-Once fragrant, add bee hoon and stew to allow stock to absorb \n-Once almost ready, add prawns and steam till stock is absorbed \n-If too light, add some dark soy sauce \n-Once colour is brown, serve hot.",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "air_fried_salmon_head",
    name: "Air fried Salmon Head",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["1 Salmon head – cleaned and halved", "Lemon slices – 2pcs", "Salt", "Black pepper"],
    instructions: "•\tWash and pat dry salmon head with paper towels\n•\tCoat with salt and pepper\n•\tPlace fish, cut side down, in air fryer\n•\tAt 200 degrees heat, grill for 7-8 mins on one side, then flip over and grill another 7 mins or so till cooked\n•\tDrizzle with lemon juice and serve hot.",
    servings: 2,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "stir_fried_nai_bai_with_mushrooms",
    name: "Stir Fried Nai Bai with Mushrooms (Mr Hong recipe)",
    type: "veg_side" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Nai bai", "Mushrooms (sliced)", "Aromatics", "Garlic (sliced) – 2 to 3 cloves", "Ginger (sliced) – one small piece", "(Optional) Red chilli – 1 sliced", "Fish marinade", "Sheng Yu slices", "Salt", "White pepper", "Huatiao wine (a bit)", "Mix well first, then add:", "Cornstarch", "Oil", "Gravy:", "Huatiao wine – 1 – 2 tbsps", "Potato starch – 1 tbsp", "Water", "Seasonings:", "Salt", "Pepper", "Sugar", "Fish sauce (to taste)"],
    instructions: "•\tSlice aromatics and mushrooms, set aside\n•\tCut and soak nai bai in water with salt, wash well and leave for 10 mins.\n•\tBoil a pot of water, add salt and oil. Once boiling, half cook nai bai for 2-3 mins\n•\tDrain and set aside\n•\tHeat a wok, stir fry garlic and ginger till fragrant. \n•\tAdd mushrooms\n•\tAdd fish slices, then nai bai\n•\tAdd seasonings\n•\tAdd gravy & water (taste test before serving)",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "master_sauce",
    name: "Master Sauce",
    type: "rice_noodle_one_pot" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Note: Use same measuring tool (ladle/ tablespoon, etc throughout!)", "Oyster sauce – 1 tbsp", "Fish sauce (thai) – 1 tbsp", "Dark soy sauce – ¼ tbsp (for colouring)", "Sugar – 1 tbsp", "Chinese cooking wine (Huatiao) – 1 tbsp", "Maggie seasoning sauce – 1 tbsp", "Light soy sauce – 3 tbsps", "Sesame oil (optional)/ chicken oil (see chicken rice recipe) – ½ tbsp", "Water/ Chicken stock (in 1:1 ratio to a combination of the above ingredients)"],
    instructions: "Bring the above mixture to a boil and turn off heat\nStore in chiller for up to 1 week (always taste before using, throw if sour!)",
    servings: 4,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "claypot_ee_mee",
    name: "Claypot Ee-Mee (adapted from Made with Lau recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Ee-mee — 3/4  - 1 piece", "Chicken breast — 1 small piece, sliced", "Prawns — ~3–4 pcs", "Leafy bai cai — a bunch", "White mushrooms — 6–7 pcs, halved", "Carrot — 1 small piece, sliced", "Fish slices (optional) — ~3 pcs", "Ginger slices — 6–7 pcs", "Green onions (separate white & green) — 5–6 pcs", "(Chicken/ Prawn marinade): salt, cornstarch, water", "(Fish marinade): salt, pepper, corn flour, sesame oil (a bit)", "Gravy — for 1 portion (not the ×2 batch):", "Salt — ½ tsp", "Sugar — 1 tsp", "Chicken bouillon — 1 tsp", "Oyster sauce — 1–1.5 tbsp", "Water/chicken stock — 1.5–2 Chinese bowlful", "Cornstarch slurry — 1 tbsp", "Sesame oil — 1 tsp (added at the end)", "(Your notes also show a ×2 version if you ever want a bigger gravy batch: salt 1 tsp, sugar ~1.5 tsp, bouillon 2 tsp, oyster sauce 3 tbsp, water/stock ~4 bowlful, cornstarch slurry ~1.5–2 tbsp.)"],
    instructions: "1) Boil water & add noodles, cook until boiling. Remove when cooked, set aside.\n2) In a wok, stir-fry ginger & green onion stems in oil. Add chicken, prawns, fish. Don't need to cook till 100% done — 80% done, set aside.\n3) If oil in wok is enough, heat & fry carrots. Then add veg stems & mushrooms.\n4) Add stock/water, simmer for 2–3 mins.\n5) Add gravy & cornstarch slurry, stir well.\n6) Add noodles, chicken & prawns back. Add veg leaves.\n7) Leave the fish for later as it may crumble.\n8) Cook till noodles are soft & ingredients cooked.\n9) Add fish & green onion leaves. Top with sesame oil, taste test to ensure it's OK.\n10) Serve hot.",
    servings: 1,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "white_bee_hoon",
    name: "White Bee Hoon (Spice N Pans recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Hsinchu (TW) beehoon — 150g, soaked", "Chicken stock — 1L (diluted: 500ml stock + 500ml water)", "Egg — 3", "Chopped garlic — 4–5 cloves", "Veg (kailan — a few bunches)", "Prawns — ~6, whole, in shell", "Chicken", "Lala & squid (optional) — 8 pcs", "Salt, pepper — to taste", "Soy sauce — 1 tbsp", "Huatiao wine — 1 tbsp", "Sesame oil — 1 tbsp", "Cooking oil", "Cornstarch solution"],
    instructions: "1) Heat wok & add cooking oil + sesame oil.\n2) Add some chopped garlic (not all) & fry till fragrant.\n3) Add beehoon, stir well, set aside on a plate.\n4) Add another tbsp of oil, fry remaining garlic.\nWhen fragrant, add chicken stock.\n5) Add soy sauce (for flavour). Cover & allow to boil.\n6) Once boiling, add beehoon back in.\n7) Add beaten egg.\n8) Add seafood & veg.\n9) Cover with lid for another 5 mins till boiling.\n10) Taste test — add salt/sugar/pepper to taste.\n11) Stir well & add starch solution to thicken as needed.\n12) Sprinkle huatiao wine & mix. Serve.",
    servings: 3,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "stir_fried_veggies_with_protein_mushroom",
    name: "Stir fried veggies with protein, mushroom and instant noodles/ Korean udon",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Veggies of your choice", "Mushrooms 1 pc (sliced)", "Instant noodles", "Chicken/ Prawns (marinate in salt, white pepper, cornstarch)", "(Aromatics)", "Garlic (1-2 cloves, chopped)", "Green onion (separate white & green part) - 1-2 stalks", "Ginger - 3-4 pcs", "White onion (1/4 piece, sliced)", "(Gravy)", "Thai oyster sauce - ~1 tbsp", "Golden mountain sauce - ~1 tbsp", "Sugar - 1/2 tsp", "Water", "Cornstarch - ~1 tsp"],
    instructions: "1) Marinate proteins of choice\n2) Boil water and cook noodles halfway. Drain & set aside.\n3) Stir fry aromatics till fragrant\n4) Add proteins, mushrooms and veg stems and stir fry\n5) Add gravy\n6) Add water\n7) Add instant noodles back in and mix well. Cook till all ingredients softened",
    servings: 1,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "air_fried_cod_fillets_with_nanban_sauce_",
    name: "Air-fried Cod fillets with Nanban sauce/ Lemon juice",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Cod fillets – 2 slices", "1 Egg", "Corn flour", "Panko bread crumbs", "Garlic powder", "Salt", "Black pepper", "Nanban sauce (from Cooking with Dog) – 2 servings", "1 hard boiled egg - sliced (boil for 5-6 mins, leave in hot water for 5 mins)", "Yellow Onions – ¼ piece (chopped, rubbed with salt, rinsed and dried well with paper towel)", "1 gherkin (mini cucumber) - chopped", "Kewpie mayo – 3 tbsp", "Salt & pepper", "Milk – 1 tbsp", "Chop egg, onions and gherkins", "Add salt, pepper, milk, mayo to the above mixture and mix well."],
    instructions: "1)  Cut cod into pieces, wash and dry with paper towels\n2) Coat with salt, black pepper and garlic powder\n3) Prepare 3 bowls – 1 for corn flour coating, 1 beaten egg, 1 for panko bread crumbs\n4) Dip fish into corn flour, followed by egg wash then panko crumbs\n5) Line air fryer with aluminium foil, drizzle some olive oil on base and also spray over the fish slices\n6) Heat for 6 mins on one slide, then flip over and heat another 6 mins till fish is fully cooked and crispy",
    servings: 3,
    cuisineType: "Western" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "fried_tanghoon",
    name: "Fried tanghoon (At Sunrice recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Tanghoon – 1 handful", "Charsiew (chopped)", "Beansprouts – 1 handful", "Egg – 2", "Spring onion – for garnish", "Garlic – chopped (2-3 tablespoons)", "Oil", "Prawns (peeled and no shell) – a few", "Chicken stock", "Fish sauce/ master sauce", "Dark soy sauce (for colour)", "Oyster sauce", "Dried mushroom (rehydrated and sliced) – 2 pieces"],
    instructions: "1) Fry chopped garlic, add egg and scramble. Set aside when cooked\n2) Add more oil to wok, then add tanghoon and fry a bit\n3) Add prawns and meat\n4) Add mushroom\n5) Stir fry, then add chicken stock and fish sauce/ master sauce\n6) Add some dark soy sauce and oyster sauce for color\n7) Add beansprouts, then stir fry everything until cooked.\n8) If the tanghoon sticks to the wok, means oil not enough! Can adjust heat as needed along the way.\n9) Taste test to see if salty and fragrant enough (if not, adjust with chicken stock/ master sauce/ fish sauce/ oyster sauce, etc)",
    servings: 3,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "hokkien_mee",
    name: "Hokkien Mee (At Sunrice recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Egg - 2", "Medium-sized cooked and peeled Prawns with tail – a few", "Squid (parboiled and sliced into rings) – a few pieces", "Pepper", "Prawn stock (can also put pork bones and prawn shells)", "Chopped garlic (need a lot)", "Leek (chopped into 2 inch pieces)", "Beansprouts – 1 handful", "Yellow noodles – 1 fistful", "Laksa noodles (same amount as yellow noodles) – 1 fistful", "Fish sauce", "Oil"],
    instructions: "1) Put fish sauce inside egg\n2) Sprinkle some pepper on noodles\n3) Heat wok and fry garlic in oil. Add fish sauce, then egg mixture and stir fry. \n4) When egg is almost cooked, add yellow noodles and laksa noodles. Stir fry the mixture. \n5) Add 2-3 ladlefuls of prawn stock (must be soupy)\n6) Add squid rings (if any)\n7) Top up with stock if needed\n8) Taste test\n9) Add prawns, leek, beansprouts \n10) Top up with prawn stock if mixture becomes too dry!\n11) Fry until the gravy turns yellowish and thickened. \n12) Can add a bit of oil (for shine) before serving",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "chicken_rice",
    name: "Chicken rice (At Sunrice recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: true,
    isFavourite: false,
    isStaple: false,
    ingredients: ["(Flavoured Chicken oil):", "Chicken fat (can combine with veg oil if not enough)/ Lard", "Pandan leaves  - 2 strips tied into a bunch", "Garlic cloves (peeled) – approx. 10-12", "Ginger (preferably old, with skin on) - thickly sliced", "Lemongrass – 2-3 stalks (smash the thick part of the stalk before use)!", "Shallots – peel & keep whole (abt 10-12pc or more)", "White Sesame oil (Oh Chee Seng brand)", "Chicken:", "1.2 kg Whole chicken, fat removed and kept aside", "3 stalks Spring onion", "50 gm Old ginger, bruised", "1 tsp Salt", "Water, as needed", "Rice:", "240 g Jasmine rice, washed & drained", "4 cups Chicken stock", "50 g Old ginger, bruised", "5 nos Garlic, bruised", "3 nos Pandan leaves, tied into a knot", "1 tsp Salt", "Ginger Sauce:", "25 g Young ginger", "125 ml Chicken stock", "1 Tbsp Salt", "1½ tsp Sugar", "Chilli Sauce:", "100 g Fresh chilies", "4 nos Garlic, peeled", "2 nos Shallots, peeled", "3 Tbsp Calamansi juice", "1 Tbsp Vinegar", "100 ml Chicken stock", "2 tsp Sugar", "2 tsp Salt", "3 cm Young ginger", "Seasoning:", "2 Tbsp Chicken stock", "2 Tbsp Light soy sauce", "1 Tbsp Sesame oil"],
    instructions: "Steps to make fragrant chicken oil:\nHeat oil on high flame. \nAdd shallots, ginger\nCook oil mixture on high heat (bubbling) and ingredients are browned and fragrant. \nAdd lemongrass and garlic. Finally, add pandan leaves. Be careful not to burn!\nAdd a few dashes of sesame oil after heat is turned off.\nStore in chiller (animal fat can’t keep for too long!)\nCan use to fry veg, cook chicken rice\n\nChicken: 3. Rub the inside and outside of the chicken with some salt. Stuff with spring onions and bruised ginger. 4. In a large pot, boil enough water to cover the chicken. Add the chicken to the boiling water, turn the heat low, cover and leave for 10 mins. Turn off the heat and let it continue cooking for another 20 mins. 5. Plunge the cooked chicken in ice water for 2 minutes. Set aside. 6. With an S-hook, hook the chicken and hang it to dry.\n\nChilli sauce: 7. Grind all the ingredients in a blender and set aside.\n\nGinger sauce: 8. Grind all the ingredients in a blender. Set aside.\n\nSeasoning: 9. Mix all ingredients together well. Set aside.\n\nRice: 10. Heat the chicken fat in a wok over medium heat and fry the garlic and ginger till fragrant (about 2 minutes). 11. Add the rice and lightly fry till well-coated with oil. Transfer the rice into a rice cooker. 12. Add 4 cups of chicken stock, salt and pandan leaves, and cook till done. 13. Fluff before serving. 14. Debone the chicken. Cut into 8 portions. Drizzle seasoning over the chicken. Serve the chicken and rice with the chilli sauce and ginger sauce.",
    servings: 3,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "sliced_fish_soup",
    name: "Sliced Fish Soup (At Sunrice recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Fish slices - 5 pcs", "Ginger - a small pc (sliced)", "White cabbage/ Lettuce", "Tomato slices (2 pcs)", "Fish stock / Chicken or prawn stock – 3-4 ladleful", "Fish sauce - 1 tsp (to taste)", "Huatiao wine - 1 tsp (to taste)", "Beehoon", "(Fish marinade):", "Fish sauce", "Huatiao wine", "Sugar (to tenderise fish) – 1 pinch", "Pepper – 1 pinch", "*Use gloved hand to rub fish slices until piak piak slimy sound is heard! (means fish proteins have come out = seasoned)", "Add some cornstarch/ tapioca powder (to smoothen texture)"],
    instructions: "1.\tHeat stock till boiling (bubbling hot)\n2.\tRemove scum (if any)\n3.\tAdd ginger and veg (Chinese cabbage) \n4.\tAdd tomato slices\n5.\tCook for 3-5 mins at a boil (keep a high flame at all times)\n6.\tAdd beehoon\n7.\tAdd fish sauce (half tbsp), Huatiao sauce (to taste - add around 1 capful)\n8.\tAllow soup to boil (bubbling hot) first\n9.\tThen add fish slices\n10.\tIf you want to add milk, add at this point.\n* Note: Evaporated milk needs to be broken – i.e. cooked at high heat for 3-5 mins before serving! (otherwise will have overly milky taste)\n12.\tTaste test, if not enough add fish sauce & Huatiao sauce to adjust\n13.\tTop with pepper before serving.",
    servings: 1,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "hong_kong_style_egg_noodles_at_sunrice_r",
    name: "Hong Kong Style Egg Noodles (Wet) - At Sunrice Recipe",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Prawns", "Char siew", "Lettuce/ Green veg/ Beansprouts", "Egg noodles", "Garlic", "Master sauce", "Egg", "Chicken / prawn Stock", "Green onions (as topping)"],
    instructions: "1) Parboil seafood and other ingredients in hot water and set aside\n2) In a Hot wok, add cold oil (prevents from sticking to wok!)\n3) Add garlic & magic sauce\n4) Add beaten egg and stir\n5) Add prawns & other ingredients (e.g. cooked fishcake, boiled beansprouts, boiled white cabbage, fresh mushrooms, charsiew, etc)\n6) Add magic sauce\n7) Add loosened egg noodles\n8) Stir fry\n9) Once you can smell fragrance, add seafood stock and stir fry till dry\n10) Add pepper (if you want)\n11) Add 1 more ladleful of stock \n12) Taste test to see if noodles are cooked\n13) If noodles are too hard, add more chicken/ prawn stock. If not salty, add master sauce\n14) Stir fry till drier.\n15) Add spring onions as toppings and give it a light stir before serving",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "soy_honey_glazed_chicken",
    name: "Soy honey glazed chicken",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Chicken breast (sliced thinly)", "Marinade:", "Salt (a bit)", "White pepper", "Garlic powder", "Cornstarch", "Sauce:", "Soy sauce - 1.5 tsp", "Oyster sauce - 1.5 tsp", "Honey - 1.5 tsp", "Chopped garlic (1 clove)"],
    instructions: "1) Wash chicken and pat dry.\n2) Coat with a bit of salt, white pepper, garlic powder and corn starch\n3) Chop 2 cloves of garlic finely\n4) Mix sauce\n5) Pan fry chicken till golden brown, then pour sauce over it.",
    servings: 1,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "stir_fried_dry_instant_noodles_with_veg_",
    name: "Stir fried dry instant noodles with veg and chicken/ prawns",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Instant noodles", "Protein of choice (chicken/ prawns) - a handful", "Veg of choice", "Oyster sauce (thai)- 1 tsp", "Health Boy sauce - 1 tsp", "Sugar - 1/2 tsp", "Water (as needed)", "Marinade:", "Cornstarch", "Pepper", "Garlic powder", "Salt"],
    instructions: "1) Marinate protein of choice\n2) Boil water and half cook instant noodles. Drain and set aside to cool.\n3) Make sauce by combining sugar, water, oyster sauce and Healthy Boy sauce.\n4) Stir fry  protein, veg, cooked noodles and gravy till done.",
    servings: 4,
    cuisineType: "Mixed" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "chicken_claypot_rice",
    name: "Chicken Claypot Rice (At Sunrice recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Rice:", "150 g Jasmine rice", "150 ml Chicken stock (for soaking/cooking rice)", "10 g Ginger, sliced thinly", "1 no Garlic, chopped", "150 ml Chicken stock", "30 g Chinese sausage", "10 g Salted fish, sliced thinly", "Chicken:", "100 g Boneless chicken thigh, cut into cubes", "10 g Ginger, sliced thinly", "1 no Garlic, chopped", "1 Tbsp Oil", "1 no Shitake mushroom", "2 Tbsp Water", "Marinade:", "1 Tbsp Oyster sauce", "½ Tbsp Dark soya sauce", "White pepper, to taste", "Garnish:", "Spring onion, as needed", "Red chillies, sliced (optional)"],
    instructions: "Place the boneless chicken thigh in a bowl, add in the seasonings to marinate and refrigerate for 30 minutes.\nHeat up the claypot, add 2 Tbsp oil and fry the salted fish until crispy. Set aside.\n\nRice: \n-Wash and rinse the rice. Soak the rice in water for 20 minutes. Strain and set aside. \n- Heat up the claypot and add 2 tablespoons of oil. Add in the ginger, garlic, and stir-fry until fragrant. \n- On high heat, add in the rice, stir for 30 seconds and add chicken stock. Cover it. \n- Once the stock is boiling, reduce heat.\n\nChicken:\n- While the rice is being cooked, in a separate pot, heat up 1 Tbsp oil, add ginger and garlic. \n- Add in marinated chicken and stir well. \n- Add in water and 2 Tbsp dark soya sauce, stir-fry until chicken is cooked.\n\nTo assemble the claypot rice: \n- When the liquid in the rice is almost dry, add chicken, Chinese sausage, and salted fish on top of the rice. \n- Cover and turn up the heat, continue cooking the rice until it is fragrant, remove it from the stove. \n- Garnish with spring onion and serve hot.",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "hokkien_fried_prawn_noodles",
    name: "Hokkien Fried Prawn Noodles",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["50 g Medium-sized squid, cleaned and cut into rings", "150 g Medium-sized prawns, shell removed and deveined (leave tail on; keep shell aside)", "2 Tbsp Cooking oil", "2 Tbsp Garlic, finely chopped", "2 nos Eggs", "100 g Bean sprouts", "1½ cup Seafood stock", "200 g Laksa noodles", "150 g Hokkien noodles", "1½ Tbsp Fish sauce", "½ tsp Ground white pepper", "1 bunch Chives, cut 2 cm long", "Prawn stock:", "2 cups Water", "1 Tbsp Oil", "Prawn heads and shells (from above)", "Garnish:", "1 no Calamansi, sliced in half", "1 tsp Fried shallots", "Accompaniment: Sambal belacan"],
    instructions: "Prawn stock: \n3. Heat up oil in a pot. Stir-fry prawn heads and shells till they turn red. \n4. Add water and let it boil for 5 mins.\n 5. Strain the stock and set aside.\n\nNoodles: \n6. Heat oil in a wok over high heat. Add chopped garlic, eggs and bean sprouts. \n7. Stir-fry for a minute. Add prawn stock and bring to a boil. \n8. Reduce heat to medium. Stir in laksa noodles, hokkien noodles, squid rings and prawns; simmer until noodles are cooked. Cover with a lid; add more stock if too dry. Noodles should be well-coated with sauce. \n9. Season with fish sauce and white pepper. Add the chives. Simmer for a minute more until chives are tender. \n10. Garnish and serve hot.",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "sliced_fish_bee_hoon_soup",
    name: "Sliced Fish Bee Hoon Soup",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["150 g Dry bee hoon, soaked in warm water until soft", "20 g Chinese white cabbage (Xiao Bai Cai), washed and trimmed into 2-inch lengths", "1-2 slices of Tomato, cut into wedges", "Soup:", "10 g Ginger, sliced", "1 stalk Spring onion, cut into 2 cm lengths", "300 ml Fish stock", "200 g Sliced fish (snakehead)", "30 ml Milk (optional)", "1 tsp Chinese cooking wine", "Seasoning:", "1 tsp Fish sauce", "1 tsp Sesame oil", "White pepper, to taste"],
    instructions: "Make Fish stock by frying fish bones with ginger, then pouring hot water over it.\nMarinate fish slices with cornflour, salt, pepper, oil.\nSoak thin beehoon in water till softened.\nIn a pot, Add fish stock, fragrant oil and ginger slices. Cook till boiling.\nAdd tomatoes\nAdd beehoon, then vegetables and cook till soft. \nAdd fish sauce and Chinese wine to taste\nAdd fish slices, remove from heat when fish slices are cooked. \nServe with chilli and any garnishes (white pepper, green onions, fried shallots, etc)",
    servings: 2,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "sliced_fish_soup_2",
    name: "Sliced Fish Soup (216 Mr Chua recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "fish" as const,
    hasVeg: true,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Fish Soup base:", "Bian yu (fried)", "Batang Fish Bones", "Pork Bones (Da gu)", "Rice water/ rice (dunk into soup at the end)", "Bonito flakes", "Kelp", "Ikan bilis"],
    instructions: "",
    servings: 1,
    cuisineType: "Cantonese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "tod_mun_pla_angsana_s_recipes",
    name: "Tod Mun Pla (Thai Fish cakes) - Angsana's recipes",
    type: "protein_main" as const,
    protein: "fish" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Boneless Mackerel fish filet/ Fish paste – 2 pieces (~300g)", "Cold/ Ice water – ¼ cup (add water bit by bit as you grind)", "Red curry paste (see above recipe) – 3 tbsp", "Salt – ½ tsp", "Sugar – 2 tsp", "Egg - 1", "Kaffir lime leaves (rolled and cut finely) – 6 pcs", "Long beans (chopped) – 2 long ones", "(Optional) Fish sauce – 1 tbsp"],
    instructions: "'- Remove fish skin and any bones, Scrape fish meat off the skin with a metal spoon. \n- Blend fish in grinder and add cold/ ice water bit by bit. (Alternative: put in freezer for 30 mins before blending)\n- To the fish mixture, add red curry paste, salt, sugar, egg and kaffir lime leaves. Stir well with a spoon or your hand in a big mixing bowl in 1 direction (like making a cake mixture) until the paste thickens. \n- Test if the mixture sticks to your wet hand when shaping into patties, if it doesn’t stick it is ready.\n- In a medium heated wok with oil, shape fish cakes and drop slowly into hot oil. For each fish cake, dip hand into a cold water bowl before shaping another patty! \n- Fry till golden brown and serve with dressing sauce in a plate.",
    servings: 4,
    cuisineType: "Thai" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_red_curry_paste",
    name: "Thai Red Curry Paste (Angsana's recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["15 small dried and 5 big dried red chillis, cut into small pieces and soak in water for 10 mins", "½ tsp coriander seeds", "½ tsp cumin seeds", "½ tsp white peppercorns", "Lemongrass – 2 stalks (cut from the bottom until you don’t see the purple anymore), then chopped finely", "1 tbsp finely chopped galangal (ingredients needs to be fine to make it easy to pound!)", "3 tbsp finely chopped shallot", "2 tbsp (~3 cloves) finely chopped garlic", "3 coriander roots, finely chopped", "½ tsp finely grated kaffir lime peel", "¼ tsp salt", "1 tsp shrimp paste"],
    instructions: "- Roast coriander seeds, cumin seeds, and white pepper seeds in a wok (no oil), until the seeds turn fragrant / start popping. \n- Crush the seeds into a fine powder in a mortar\n- Add chillies, salt, crush till fine\n- Add lemongrass and galangal, crush till fine\n- Add garlic, shallots, coriander roots and crush till fine\n- Add kaffir lime and shrimp paste, crush and mix well until all ingredients become like a paste. (can also use a food processor!)\n(Note: Mixture keeps for 1 month in a fridge.\nFor yellow curry, add 1 tbsp curry powder and big red chillies. For green chilli, add fresh green chillies – 10-20 pcs or as much as you like and fresh coriander (stem & leaves)!)",
    servings: 4,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "caramelised_chicken_thigh_pork_belly_goe",
    name: "Caramelised chicken thigh/ pork belly (Angsana's recipe) - goes with Thai Prawn Paste fried rice",
    type: "protein_main" as const,
    protein: "chicken" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Chicken thigh (cut into small pieces)", "Palm sugar – 2 tbsp", "Dark sweet soy sauce – 2 tbsp", "Finely chopped garlic – 1 tbsp (3 cloves)", "1 tsp white pepper powder", "1 tsp salt", "1 cup water (just enough to cover the meat)"],
    instructions: "•\tPrepare caramelized chicken/ pork:\n-\tSlice fatty chicken into small cubes and set aside.\n-\tOver medium high heat in a wok, add water and dissolve palm sugar into it\n-\tAdd dark sweet soy sauce, then add chopped garlic and salt\n-\tAdd meat into it and simmer on low heat till caramelized and sticky (approx. 20 mins)",
    servings: 1,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_prawn_paste_fried_rice",
    name: "Thai Prawn Paste Fried Rice (Angsana's recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: true,
    isFavourite: true,
    isStaple: true,
    ingredients: ["Sour mango shreds", "Shallots", "Fried egg (cut to slices)", "Fried dried shrimp", "Stewed fatty chicken/ pork cubes", "Long beans (cut to small bits)", "Red chillies", "Lime slice (for squeezing)", "Overnight (hard) rice"],
    instructions: "•\tPrepare caramelized chicken/ pork (see recipe above) and set aside\n•\tSlice shallots into pieces\n•\tSlice long beans into small bits\n•\tCut red chillies and lime\n•\tShred green mango\n•\tFry 2 beaten eggs mixed with soy sauce and a dash of pepper, roll and slice into thin pieces\n•\tHeat some oil in a wok and fry dried shrimp till crispy. Set aside.\n•\tLeave some oil in the wok, add 1 tbsp of shrimp paste to dissolve. Add long beans and fry a while. Add 2 scoops of rice and mix well.\n•\tWhen rice is done, plate and add various toppings surrounding it.",
    servings: 1,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "kangkong_belachan_home_cooking_with_somj",
    name: "Kangkong Belachan (Thai) - Home Cooking with Somjit",
    type: "veg_side" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: true,
    ingredients: ["600 g kangkung (water spinach / morning glory)", "2 red chillies", "3 dried large chillies", "3 cloves garlic", "5 shallots", "1 tbsp shrimp paste (belacan)", "1 tbsp light soy sauce", "1 tbsp dried shrimp (udang kering)", "1 tbsp sugar", "2 small pieces asam keping", "6 bird's eye chillies (optional)", "Water, as needed", "Cooking oil"],
    instructions: "1. Make chilli paste",
    servings: 3,
    cuisineType: "Thai" as const,
    spiceLevel: "light-medium" as const,
    createdAt: 1789523941298,
  },
  {
    id: "chicken_pho",
    name: "Chicken Pho (Provincial Table recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "chicken" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: true,
    isStaple: false,
    ingredients: ["Spring onion 4-5 stalks – with both stem & green part (slice some of the green part for topping later)", "Onion (1/2) + some sliced for topping later", "Ginger (without skin)", "Kampong chicken thigh (for eating)", "Chicken bones (for stock)", "Spices (cinnamon, star anise, cardamom, coriander seed, fennel, dried ginger, cloves) – either fresh or use ready-packed pho spice bags", "Vegetarian stock", "Corn (2 pcs)", "Carrot (1/2)", "Gicama (1/2)", "Korean pear (1 pc)", "Chicken stock", "Fresh coconut water (1/2 pot)", "Chicken stock (1/2 pot) – boil bones for 3-4 hours in advance!", "Veggies", "Basil leaves", "Beansprouts", "Lettuce", "Lime", "Chilli"],
    instructions: "•\tBoil chicken bone stock for till ready, then add chicken to be consumed and cook on low heat for ~45 mins)\n•\tGrill spring onions over fire (more fragrant than pan-fry!)\n•\tGrill halved onion over fire\n•\tGrill ginger pieces (no skin) – over fire\n•\tUsing a mortar, break spices into smaller pieces\n•\tIn a pan, toast spices mix till fragrant. Set aside to cool, then pack in a teabag and tie it securely to prevent leakage\n•\tAdd grilled spring onion, ginger and onions into stock. \n•\tWhen spices mix has cooled, add it to the soup stock as well\n•\tCook pho\n•\tPeel chicken to shreds and add to pho, top with green onions, onions and beansprouts.\n•\tPour stock over the pho\n•\tServe with greens (basil leaves, lettuce, etc) & lime + chilli",
    servings: 1,
    cuisineType: "Vietnamese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "vietnamese_yoghurt",
    name: "Vietnamese Yoghurt (Makes 7 full glasses in Severin yoghurt maker)",
    type: "rice_noodle_one_pot" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Condensed milk – 1 can (~ 390g for Milkmaid brand)", "Milk – ~1.5 condensed milk sized cans (~450 for Meiji milk medium sized)", "Emmi Plain Yoghurt (200g) / Australian Greek yoghurt (145g)/ 1 cup of leftover yoghurt as starter - ~ 100-200g", "Boiling hot water – 1.5 cans", "Room temp water - ~ ½ to 1 can (to taste, for dilution of mixture in case too sweet)", "[Note: Total liquid (apart from the condensed milk) should add up to ~ 3.5 to 4 cups!]", "Tools needed:", "Fine sieve", "Large pot/ bowl", "Whisk", "Spoon & ladle"],
    instructions: "-\tPour 1 can of condensed milk in large bowl/ pot\n-\tAdd 1.5 cans boiling hot water and rinse can\n-\tAdd Greek yoghurt \n-\tMix till all dissolved\n-\tAdd room temp water to taste before finalising\n-\tSieve mixture & pour into yoghurt cups (take care not to form bubbles on the surface!)\n-\tCover the cups and place in Severin yoghurt maker (or put in hot water bath/steamer/ oven covered with a cloth)\n-\tLeave overnight (~ 8 hrs – leave longer for more tart taste)\n-\tRefrigerate for at least 3 hours before serving (best if can let set for 1 day as the flavour stabilizes)\n-\tCan serve with fruits or a squeeze of Viet lime\n-\tFinish in 1 week (max 10 days)",
    servings: 4,
    cuisineType: "Vietnamese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "thai_nam_yum_dipping_sauce",
    name: "Thai Nam Yum Dipping Sauce (Fitous Thai Kitchen recipe)",
    type: "rice_noodle_one_pot" as const,
    protein: "tofu" as const,
    hasVeg: true,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Handful of garlic", "50g Coriander root", "100g Coriander leaves", "4 tbsp fish sauce (although we used an extra one after tasting) Squid brand is best", "4  limes (although we used an extra one after tasting)", "1 Tbsp White vinegar", "2 Tbsp Palm sugar", "1 Tbsp White sugar", "4/5 Green Birds eye chilli", "20 Red birds eye chilli"],
    instructions: "",
    servings: 4,
    cuisineType: "Thai" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
  {
    id: "oden",
    name: "Oden (YT – Ochikeron & Tabi's Kitchen. Allow 1–2 days prep!)",
    type: "protein_main" as const,
    protein: "seafood" as const,
    hasVeg: false,
    isRice: false,
    isFavourite: false,
    isStaple: false,
    ingredients: ["Soup base:", "Water – 2000 ml", "Ma kombu – 1 pc (15cm/6in)", "Niboshi (small dried sardines) – ~50g", "Bonito flakes / bonito pack – 50g / 1 pkt", "Soup seasoning:", "Sake – 100 ml", "Soy sauce – 50 ml", "Mirin – 2 tbsp", "Salt – ~1 tsp", "Sugar – ~1–2 tbsp (to taste)", "Ingredients:", "1 daikon radish", "Kome no togijiru (cloudy rice water)", "Kibun oden set (fish cakes, chikuwa, hanpen, etc.)", "Eggs – 2 pc", "Japanese mustard sauce (optional)"],
    instructions: "Steps – daikon prep:\n\nPeel skin off daikon with a peeler\nCut into 2cm slices\nDo mentori (plane off the corners)\nParboil daikon in cold rice water; bring to boil, boil ~15 mins (till clear)\nMake X incisions on both sides of each piece\nWash in cold water and set aside\n\nSteps – soup stock:\n7. Remove heads and guts of niboshi\n8. Put water in a deep pot, soak niboshi and kombu for 1 hour\n9. Heat pot; before it boils, add katsuobushi pack, cook on low 2–3 mins\n10. Remove kombu and other ingredients; strain stock\n11. Add seasonings\n12. Add daikon, bring to a boil, turn to low, simmer 15 mins (can leave in fridge overnight)\n\nSteps – finishing:\n13. Boil fishcake items in hot water to remove excess oil\n14. Add ingredients to soup stock\n15. Cover and simmer on low for 1 hr\n16. Set aside 5 hrs to soak before serving\n\nBoiled egg for oden:\n17. Boil water till boiling, add salt\n18. Add egg, cook ~10–11 mins\n19. Flip egg around while cooking to prevent yolk settling on one side\n20. Cool under tap water\n21. Peel and put into soup stock",
    servings: 3,
    cuisineType: "Japanese" as const,
    spiceLevel: "light" as const,
    createdAt: 1789523941298,
  },
];
